import {soundAnchors} from './shop-data.js';
// One gesture-activated context. Procedural textures can later be replaced by
// recordings on the same zones; there is no audio work while muted.
export function createAmbientAudio({camera,walking,shopSystem,townLife,getQuality=()=>'standard'}){
 const zones=[...soundAnchors,{id:'market',area:'town',kind:'market',position:[19,3.5,16],src:null}],gains=new Map(),sources=new Map(),triggers=[],listeners=new Set(),bells=new Set();let context=null,master=null,enabled=false,elapsed=0,period=townLife.state.period,button,lastFeet=null,steps=0,wheelTick=0,lastBellAt=-Infinity;
 for(const z of zones)gains.set(z.id,0);
 function burst(kind){if(!enabled||context.state!=='running')return;const now=context.currentTime,source=context.createBufferSource(),filter=context.createBiquadFilter(),gain=context.createGain();source.buffer=noise;filter.type='lowpass';filter.frequency.value=kind==='cat'?260:kind==='wood'?430:750;gain.gain.setValueAtTime(kind==='cat'?.007:.017,now);gain.gain.exponentialRampToValueAtTime(.0001,now+.12);source.connect(filter).connect(gain).connect(master);source.start(now,0,.15);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};}
 function bell(trigger){const key=trigger.day+':'+trigger.period+':'+trigger.id;if(!enabled||bells.has(key)||context.currentTime-lastBellAt<8)return;bells.add(key);if(bells.size>48)bells.delete(bells.values().next().value);const now=context.currentTime;lastBellAt=now;[1,2.01,2.73,3.9].forEach((partial,i)=>{const oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=294*partial;gain.gain.setValueAtTime(.018/(i+1)*Math.max(.08,1-Math.abs(camera.position.x)/210),now);gain.gain.exponentialRampToValueAtTime(.0001,now+3.2-i*.3);oscillator.connect(gain).connect(master);oscillator.start(now);oscillator.stop(now+3.3);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};});}
 townLife.onChange(state=>{if(state.period===period)return;period=state.period;const id={morning:'morningBell',evening:'eveningBell',night:'nightBell'}[period];if(id){const trigger={id,period,day:state.dayIndex,weather:state.weather};triggers.push(trigger);if(triggers.length>24)triggers.shift();bell(trigger);for(const fn of listeners)fn(trigger);}});
 let noise;
 async function enable(){const Audio=globalThis.AudioContext??globalThis.webkitAudioContext;if(!Audio)return false;try{if(!context){context=new Audio();master=context.createGain();master.gain.value=.6;master.connect(context.destination);noise=context.createBuffer(1,context.sampleRate*2,context.sampleRate);const data=noise.getChannelData(0);let seed=314159;for(let i=0;i<data.length;i++){seed=(seed*1664525+1013904223)>>>0;data[i]=(seed/4294967296)*2-1;}
 for(const [id,frequency]of [['harbor-water',420],['spring-water',650],['stream-water',480],['mill-wheel',220],['rain',1500],['nine-wind',180]]){if(zones.find(z=>z.id===id)?.src)continue;const source=context.createBufferSource(),filter=context.createBiquadFilter(),gain=context.createGain();source.buffer=noise;source.loop=true;filter.type='lowpass';filter.frequency.value=frequency;gain.gain.value=0;source.connect(filter).connect(gain).connect(master);source.start();sources.set(id,{source,filter,gain});}}
 await context.resume();for(const zone of zones){if(!zone.src||zone.unavailable||sources.has(zone.id))continue;try{const response=await fetch(zone.src);if(!response.ok)throw Error('Unavailable audio');const source=context.createBufferSource(),gain=context.createGain();source.buffer=await context.decodeAudioData(await response.arrayBuffer());source.loop=true;gain.gain.value=0;source.connect(gain).connect(master);source.start();sources.set(zone.id,{source,gain});}catch{zone.unavailable=true;}}enabled=true;lastFeet=null;label();return true;}catch{enabled=false;label();return false;}}
 function label(){if(button){button.textContent=enabled?'音：入':'音：切';button.setAttribute('aria-pressed',String(enabled));}}
 function disable(){enabled=false;context?.suspend();lastFeet=null;label();}
 function update(dt){if(!enabled)return;wheelTick+=dt;elapsed+=dt;if(elapsed<(getQuality()==='mobile'?.5:.25))return;elapsed=0;const area=shopSystem.current?.shop.id??'town',p=camera.position;
 for(const z of zones){if(!z.position||z.area!==area){gains.set(z.id,0);continue;}const x=z.position[0]+(area==='town'?0:200),d=Math.hypot(p.x-x,p.y-z.position[1],p.z-z.position[2]);gains.set(z.id,Math.max(0,1-d/(z.radius??22))*(z.gain??.35));}
 for(const [id,node]of sources){const volume=id==='rain'?(townLife.state.weather==='rain'?(area==='town'?.055:.018):0):(gains.get(id)??0)*.12;node.gain.gain.setTargetAtTime(volume,context.currentTime,.4);}
 if(wheelTick>4.3){wheelTick=0;if((gains.get('mill-wheel')??0)>.15)burst('wood');}
 if(walking.active&&!walking.state.inputBlocked){const feet=walking.state.feet;if(lastFeet){const d=feet.distanceTo(lastFeet);if(d<4&&!walking.jumping)steps+=d;else steps=0;}lastFeet=feet.clone();if(steps>.7){steps=0;burst(walking.state.profile.id==='cat'?'cat':area==='town'?'stone':'wood');}}else lastFeet=null;
 }
 document.addEventListener('visibilitychange',()=>{if(document.hidden)disable();});
 function triggerBell(id){const trigger={id,period:townLife.state.period,day:townLife.state.dayIndex,weather:townLife.state.weather};triggers.push(trigger);if(triggers.length>24)triggers.shift();bell(trigger);for(const fn of listeners)fn(trigger);return trigger;}
 function stoneResonance(){if(!enabled||context?.state!=='running')return;burst('wood');}
 return {stoneResonance,triggerBell,zones,gains,triggers,update,enable,disable,onBell(fn){listeners.add(fn);return()=>listeners.delete(fn);},attachButton(container){button=document.createElement('button');button.type='button';button.title='控えめな水音・雨・鐘・足音';button.style.cssText='border-radius:16px;padding:8px 12px;background:#e3d8c0;color:#453d30;border:1px solid #8c806a';button.onclick=()=>enabled?disable():enable();container.append(button);label();},get context(){return context},get master(){return master},get stats(){return{zones:zones.length,configured:sources.size,enabled,contexts:context?1:0};}};
}
