// One existing skiff, local lake predicates and bounded safe docks; no global
// collision scan, per-frame storage writes, or second animation loop.
export const boatDocks={lunmere:{name:'Lunmere',boat:[-420,5.88,-6],feet:[-418,6.16,-4.5],yaw:0},lake:{name:'Lake Lun',boat:[-321,5.75,-27],feet:[-321,6.15,-24],yaw:Math.PI},caerith:{name:'Isle of Caerith',boat:[-367,5.75,-51.5],feet:[-367,6.12,-53.3],yaw:Math.PI}};
// Docking follows each physical pier edge, rather than a single mooring point.
export const pierBounds={lunmere:[-419.2,-416.8,-7,-1.8],lake:[-324.5,-315.5,-25.2,-22.8],caerith:[-368.2,-365.8,-59.6,-52.6]};
export function nearbyDock(x,z){return Object.entries(pierBounds).find(([,b])=>Math.hypot(x-Math.max(b[0],Math.min(b[1],x)),z-Math.max(b[2],Math.min(b[3],z)))<=1.85)?.[0]??null;}
export function lakeSurfaceHeight(x,z){const clamp=n=>Math.max(0,Math.min(1,n));return 5.65+.13*clamp((z+26)/4)*clamp((-x-370)/4);}
export function navigableLake(x,z){
 if([-322,-327,-332,-337].some(rx=>Math.hypot(x-rx,z+39)<1.3))return false;
 if(Math.hypot((x+367)/17,(z+76)/19)<1.15)return false;
 if(x>-339.5&&z>-57.3&&z<-46.7)return false;
 // Preserve the old western bank: reach the island through the open southern arm.
 return (x>=-468&&x<=-383&&z>=-22.5&&z<=-7)||(x>=-434&&x<=-383&&z>=-48.7&&z<=-21)||(x>=-410&&x<=-324&&z>=-107.5&&z<=-48.1)||(x>=-363&&x<=-319&&z>=-47&&z<=1)||(x>=-363&&x<=-340&&z>=-54&&z<=-44)||(x>=-423&&x<=-419&&z>=-8&&z<=-4.5);
}
export function createBoatTravel({THREE,boat,lunmere,lake,caerith,walking,camera,controls,inspections,quietStay,shopSystem,stay,regions,caerithStay,navigation,minimap,entity}){
 Object.assign(entity,{object:boat,controllable:true,docks:boatDocks,routePossibilities:['lunmere','lake','caerith']});
 const rider=new THREE.Group();boat.add(rider);const cloth=new THREE.MeshStandardMaterial({color:0x748374,roughness:1}),skin=new THREE.MeshStandardMaterial({color:0xbca286,roughness:1});const body=new THREE.Mesh(new THREE.CylinderGeometry(.17,.22,.5,6),cloth),head=new THREE.Mesh(new THREE.SphereGeometry(.16,6,4),skin);body.position.set(-.2,.43,0);head.position.set(-.2,.82,0);rider.add(body,head);rider.traverse(o=>o.userData.walkSoft=true);rider.visible=false;
 let active=false,speed=0,yaw=0,lastDock=stay.data.boatDock??'lunmere';const keys=new Set(),state={position:boat.position,profile:'human',collisions:0};
 const ui=document.createElement('section');ui.className='boat-controls';ui.hidden=true;ui.setAttribute('aria-label','小舟の操作');const status=document.createElement('span'),exit=document.createElement('button');exit.textContent='降りる';ui.append(status,exit);
 for(const [code,label]of [['KeyA','左'],['KeyW','前進'],['KeyS','後退'],['KeyD','右']]){const b=document.createElement('button');b.textContent=label;b.setAttribute('aria-label','舟を'+label);b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);keys.add(code);};b.onpointerup=b.onpointercancel=()=>keys.delete(code);ui.append(b);}document.body.append(ui);
 const walkButtons=['walk','catWalk'].map(id=>document.getElementById(id)).filter(Boolean);const prompt=document.getElementById('inspectPrompt');
 const getDock=()=>Math.abs(speed)<.65?nearbyDock(boat.position.x,boat.position.z):null;
 function snap(id){lastDock=Object.hasOwn(boatDocks,id)?id:'lunmere';const d=boatDocks[lastDock];boat.position.fromArray(d.boat);yaw=d.yaw;boat.rotation.y=yaw+Math.PI/2;speed=0;entity.dockState=lastDock;entity.boardingPoint=[...d.feet];boat.visible=true;lake.rope.visible=lastDock!=='lake';lake.boat.visible=lastDock!=='lake';lunmere.mooring.geometry.setFromPoints([new THREE.Vector3(...d.feet),new THREE.Vector3(d.boat[0],6,d.boat[2])]);lunmere.mooring.visible=true;}
 function persist(id){stay.data.boatDock=id;stay.changed();}
 function begin(id){if(active||!walking.active||shopSystem.current||walking.jumping)return false;const d=boatDocks[id];if(!d||Math.hypot(walking.state.feet.x-d.feet[0],walking.state.feet.z-d.feet[2])>3.2)return false;if(id==='caerith'&&!stay.data.discoveries['region:caerith'])return false;
 quietStay.end();inspections.dismiss();snap(id);persist(id);state.profile=walking.state.profile.id;rider.visible=true;body.scale.set(state.profile==='cat'?1.2:1,state.profile==='cat'?.38:1,state.profile==='cat'?1.6:1);head.position.y=state.profile==='cat'?.53:.82;active=true;walking.setInputBlocked('boat',true);document.exitPointerLock?.();ui.hidden=false;document.getElementById('panel').classList.remove('collapsed');document.body.classList.add('boating');walkButtons.forEach(b=>b.disabled=true);lunmere.mooring.visible=false;if(lastDock==='lake')lake.rope.visible=false;entity.dockState='sailing';controls.enabled=false;regions.showRegion('lake-lun');navigation.setDestinations([{id:'boat-lunmere',name:'Lunmere船着場',short:'町',position:boatDocks.lunmere.boat},{id:'boat-caerith',name:'Isle of Caerith船着場',short:'島',position:boatDocks.caerith.boat},{id:'boat-lake',name:'Lake Lun桟橋',short:'桟',position:boatDocks.lake.boat}]);minimap.setRegion({id:'lake-lun',name:'Lake Lun · 湖上',mapBounds:{minX:-466,maxX:-304,minZ:-100,maxZ:24},roads:[]});return true;}
 function finish(id=getDock()){if(!active||!id)return false;const d=boatDocks[id],y=walking.canStandTownAs(state.profile,d.feet[0],d.feet[2],d.feet[1]);if(y===null)return false;snap(id);active=false;rider.visible=false;keys.clear();walking.setInputBlocked('boat',false);walking.relocate(new THREE.Vector3(d.feet[0],y,d.feet[2]),{yaw:d.yaw});ui.hidden=true;document.getElementById('panel').classList.add('collapsed');document.body.classList.remove('boating');walkButtons.forEach(b=>b.disabled=false);persist(id);
 if(id==='caerith')caerithStay.remember('region:caerith','湖を渡って、小さな島へ着いた。',state.profile);regions.update(1);regions.refreshArea();walking.update(0);return true;}
 function cancel(){if(!active)return;finish(lastDock);}
 walking.onLeave(cancel);regions.beforeRevisit=id=>{cancel();if(id==='caerith')snap('caerith');else if(id==='lunmere')snap('lunmere');else if(id==='lake-lun')snap('lake');persist(lastDock);};exit.onclick=()=>finish();
 function key(e){if(e.defaultPrevented||!active||/^(INPUT|SELECT|TEXTAREA)$/.test(e.target.tagName))return;if(['KeyW','KeyS','KeyA','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyE'].includes(e.code)){e.preventDefault();if(e.code==='KeyE'){if(!e.repeat)finish();}else keys.add(e.code);}}
 document.addEventListener('keydown',key);document.addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden)keys.clear();});
 for(const [id,d]of Object.entries(boatDocks)){const entry={id:'boat:board:'+id,kind:'boat',verb:'舟に乗る',label:d.name+'の小舟',object:boat,localPoint:[0,.35,0],profiles:['human','cat'],range:3.6,priority:-4,enabled:actor=>!active&&lastDock===id&&!shopSystem.current&&Math.hypot(actor.feet.x-d.feet[0],actor.feet.z-d.feet[2])<=3.2&&(id!=='caerith'||!!stay.data.discoveries['region:caerith'])};inspections.resolver.register(entry);}
 inspections.resolver.entries.get('lake:board').enabled=()=>!active&&lastDock!=='lake'&&!shopSystem.current;inspections.handlers.set('boat',e=>begin(e.id.split(':').at(-1)));
 function allowed(x,z){if(getDock()&&Math.hypot(x-boat.position.x,z-boat.position.z)<.6)return navigableLake(x,z)||Math.hypot(x-boatDocks[getDock()].boat[0],z-boatDocks[getDock()].boat[2])<1.9;return navigableLake(x,z);}
 function hullClear(x,z,a){const ex=.97*Math.abs(Math.sin(a))+.33*Math.abs(Math.cos(a)),ez=.97*Math.abs(Math.cos(a))+.33*Math.abs(Math.sin(a));return !Object.values(pierBounds).some(([left,right,near,far])=>x+ex>left&&x-ex<right&&z+ez>near&&z-ez<far);}
 function update(dt){if(!active)return;dt=Math.min(.05,Math.max(0,dt));const forward=Number(keys.has('KeyW')||keys.has('ArrowUp'))-Number(keys.has('KeyS')||keys.has('ArrowDown')),turn=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft'));speed+=(forward*2.1-speed)*Math.min(1,dt*.8);const nextYaw=yaw-turn*.55*dt;if(hullClear(boat.position.x,boat.position.z,nextYaw))yaw=nextYaw;const x=boat.position.x-Math.sin(yaw)*speed*dt,z=boat.position.z-Math.cos(yaw)*speed*dt;if(allowed(x,z)&&hullClear(x,z,yaw)){boat.position.x=x;boat.position.z=z;}else{speed*=.1;state.collisions++;}boat.rotation.y=yaw+Math.PI/2;boat.position.y=lakeSurfaceHeight(boat.position.x,boat.position.z)+.1+Math.sin(performance.now()*.0013)*.018;walking.state.feet.copy(boat.position);walking.state.yaw=yaw;camera.position.set(boat.position.x+Math.sin(yaw)*4.2,8.45,boat.position.z+Math.cos(yaw)*4.2);camera.lookAt(boat.position.x-Math.sin(yaw)*2,6.1,boat.position.z-Math.cos(yaw)*2);prompt.hidden=true;const dock=getDock();exit.disabled=!dock;status.textContent=dock?'E · '+boatDocks[dock].name+'で降りる':nearbyDock(boat.position.x,boat.position.z)?'接岸中 · 操作を離して減速すると降りられます':'湖上 · 桟橋に寄せて停止すると降りられます';if(caerithStay.lowWater&&Math.hypot(boat.position.x+379,boat.position.z+48)<6)caerithStay.remember('lake:submerged-line','水の下に、まっすぐ続く石が見えた。先は、まだ水に隠れている。',state.profile);}
 snap(lastDock);return{begin,finish,cancel,update,keys,state,docks:boatDocks,navigable:navigableLake,safeWater:(x,z,a=0)=>navigableLake(x,z)&&hullClear(x,z,a),get active(){return active},get dock(){return getDock()},get speed(){return speed},get lastDock(){return lastDock}};
}
