import {createDetailBatch} from './miniature.js';
import {capitalWards as W,capitalLinks as links,capitalRoad,capitalFacilities,capitalCharacters,capitalObservations,capitalEvents,capitalCatCounts,capitalCatTexts} from './caer-veyra-data.js';
import {buildCapitalInterior} from './caer-veyra-interiors.js';
import {evaluateConditions} from './progression-data.js';
import {extendRoyalRoad} from './violet-mire.js';
import {regionActivity} from './region-activity.js';
let liveData=null;
export const capitalWardOpen=id=>!!liveData&&evaluateConditions('capital-'+id,liveData);
export const setCapitalState=data=>liveData=data;
export const wardId=id=>'caer-'+id;
const distanceTo=(path,x,z)=>{let q={d:Infinity,y:0};for(let i=1;i<path.length;i++){const a=path[i-1],b=path[i],dx=b[0]-a[0],dz=b[2]-a[2],t=Math.max(0,Math.min(1,((x-a[0])*dx+(z-a[2])*dz)/(dx*dx+dz*dz))),d=Math.hypot(x-a[0]-t*dx,z-a[2]-t*dz);if(d<q.d)q={d,y:a[1]+t*(b[1]-a[1])};}return q;};
export function capitalWardAt(x,z){return W.find(w=>Math.abs(x-w.center[0])<w.size[0]/2&&Math.abs(z-w.center[2])<w.size[1]/2);}
export function capitalHeight(x,z){if(!capitalWardOpen('lowerWard'))return null;const w=capitalWardAt(x,z);if(w)return w.center[1];for(const p of [capitalRoad,...links.map(l=>l.points)]){const q=distanceTo(p,x,z);if(q.d<3.3)return q.y;}return null;}
export function capitalBlocked(x,z,y,profile){const w=capitalWardAt(x,z);if(w&&!capitalWardOpen(w.id))return true;for(const l of links)if(!capitalWardOpen(l.to)&&Math.hypot(x-l.gate[0],z-l.gate[2])<2.5)return true;if(w?.id==='canalWard'&&Math.abs(z+320)<3.8&&Math.abs(x+684)>6&&Math.abs(x+684)<32)return true;return false;}
export const capitalDry=(x,z,y)=>capitalHeight(x,z)!==null&&y>=7.5;
export function buildCaerVeyra({THREE,scene,box,residentScale}){
 const root=new THREE.Group();root.name='Caer Veyra';scene.add(root);const wards={},actors={},people=[],shops=[],targets=[],shells=[],catSteps=[],catRoutes=[],localPaths={},grounds=[],gates=[],windows=[],eventProps=[],observationProps={};
 const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:1});const materials={stone:mat(0xc6c0a7),honey:mat(0xcdb990),old:mat(0x787d76),roof:mat(0x455b65),copper:mat(0x68837b),wood:mat(0x756656),grass:mat(0x7d866b),water:mat(0x4a656c),paper:mat(0xd8cfb5),cloth:mat(0xa79578),skin:mat(0xba977b)};const light=mat(0xe4bb7f);light.emissive.setHex(0xffbc75);light.emissiveIntensity=.1;materials.glow=light;const oil=light.clone();oil.userData.blackoutBackup=true;materials.oil=oil;
 const proxyMaterial=new THREE.MeshBasicMaterial({visible:false});
 function proxy(x,y,z,w,h,d,name){const o=box(x,y,z,w,h,d,proxyMaterial,root);o.name=name;o.castShadow=o.receiveShadow=false;o.userData.collisionOnly=true;return o;}
 const roofGeo=new THREE.BufferGeometry();roofGeo.setAttribute('position',new THREE.Float32BufferAttribute([-.5,0,-.5,.5,0,-.5,0,1,-.5,-.5,0,.5,.5,0,.5,0,1,.5],3));roofGeo.setIndex([0,2,1,3,4,5,0,3,5,0,5,2,1,2,5,1,5,4,0,1,4,0,4,3]);roofGeo.computeVertexNormals();
 const strip=(path,width,ma,parent=root)=>{const a=[];for(let i=1;i<path.length;i++){const p=path[i-1],q=path[i],dx=q[0]-p[0],dz=q[2]-p[2],l=Math.hypot(dx,dz),nx=-dz/l*width/2,nz=dx/l*width/2;a.push(p[0]+nx,p[1]+.018,p[2]+nz,q[0]+nx,q[1]+.018,q[2]+nz,q[0]-nx,q[1]+.018,q[2]-nz,p[0]+nx,p[1]+.018,p[2]+nz,q[0]-nx,q[1]+.018,q[2]-nz,p[0]-nx,p[1]+.018,p[2]-nz);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(a,3));g.computeVertexNormals();const o=new THREE.Mesh(g,ma);o.userData.walkSoft=true;parent.add(o);return o;};
 strip(capitalRoad,6.6,materials.grass);strip(capitalRoad,4.4,materials.stone);for(const l of links)strip(l.points,6.6,materials.stone);
 const worldBatch=createDetailBatch(THREE,root,'Royal road old walls and banks');for(let i=1;i<capitalRoad.length;i++){const p=capitalRoad[i];for(const sign of [-1,1])worldBatch.add('block',materials.old,[p[0],p[1]+.4,p[2]+sign*4.3],[3,.8,.5]);}worldBatch.finish();
 const gatePiece=(x,y,z,w,h,d,ma,parent=root)=>{const o=box(x,y,z,w,h,d,ma,parent);o.userData.walkSoft=true;o.castShadow=false;return o;};
 // Layered outer gate: pedestrians use the clear central opening.
 for(const z of [-323.5,-316.5]){gatePiece(-562,8,z,3,5.5,1.5,materials.old);proxy(-562,8,z,3,5.5,1.5,"外門の柱");}gatePiece(-562,12.8,-320,3,.8,8.5,materials.honey);gatePiece(-562,8,-324,1.6,1.2,2.8,materials.wood);targets.push({id:'cv:arrival-gate',kind:'inspect',label:'王都の外門',text:'古門の下で、今日の通行を確かめている。',object:root,localPoint:[-562,9,-320],profiles:['human','cat'],range:4});
 const roadView=gatePiece(-532,7.4,-286,.8,.08,.7,materials.old);targets.push({id:'cv:royal-view',kind:'quiet-view',verb:'眺める',label:'王都を初めて望む',text:'城壁と屋根と水路橋。その間で、今日も人が動いている。',object:roadView,localPoint:[0,.2,0],range:2.8,profiles:['human','cat'],viewEye:[-530,13,-285],viewFocus:[-650,20,-375]});
 // A modest bridge and cart traces mark the change from wetland to paved road.
 strip([[-505,6.55,-267.5],[-514,6.9,-274.75]],5,materials.wood);for(const p of [[-520,7.1,-278],[-538,7.7,-294]])worldBatch.root.userData.roadTrace=p;
 for(const w of W){const [cx,y,cz]=w.center,g=new THREE.Group();g.name=w.english;root.add(g);const detail=new THREE.Group();g.add(detail);const batch=createDetailBatch(THREE,g,w.english+' buildings');const deco=createDetailBatch(THREE,detail,w.english+' details');wards[w.id]={...w,root:g,detail,batch,proxies:[],buildings:[],roads:[],crowd:[],windowGroups:[],roofItems:[]};
  const ground=gatePiece(cx,y-1,cz,w.size[0],1,w.size[1],w.id==='oldQuarter'?materials.old:materials.grass,g);grounds.push(ground);strip([[cx-w.size[0]/2,y,cz],[cx+w.size[0]/2,y,cz]],6,materials.stone,g);strip([[cx,y,cz-w.size[1]/2],[cx,y,cz+w.size[1]/2]],6,materials.stone,g);
  // Perimeter remnants keep unsupported spaces legible, with road-sized openings.
  for(let i=0;i<20;i++){const x=cx-w.size[0]/2+i*w.size[0]/19;if(Math.abs(x-cx)<5)continue;for(const sign of [-1,1])batch.add('block',materials.old,[x,y+.48,cz+sign*w.size[1]/2],[w.size[0]/19,.96,.55]);}
  const list=capitalFacilities.filter(s=>s.ward===w.id).map(s=>({...s,center:[cx+s.offset[0],cz+s.offset[1]],buildInterior:buildCapitalInterior,restable:s.type==='lodging'}));shops.push(...list);
  function building(x,z,bw,bd,bh,index,facility=null){const material=w.id==='oldQuarter'?materials.old:index%3?materials.stone:materials.honey;batch.add('block',material,[x,y+bh/2,z],[bw,bh,bd]);const collision=proxy(x,y,z,bw,bh,bd,facility?.name??w.name+'の住居 '+index);wards[w.id].proxies.push(collision);const shell={object:collision,b:new THREE.Box3().setFromObject(collision,true)};shells.push(shell);wards[w.id].buildings.push(shell);
   wards[w.id].roofItems.push({material:index%4===0?materials.copper:materials.roof,position:[x,y+bh,z],scale:[bw+.3,index%3===0?1.15:.8,bd+.3]});
   for(const sign of [-1,1]){deco.add('block',materials.wood,[x+sign*bw*.28,y+1.3,z+bd/2+.025],[.55,.8,.04]);deco.add('block',light,[x+sign*bw*.28,y+1.3,z+bd/2+.055],[.42,.6,.025]);}deco.add('block',materials.wood,[x,y+1,z+bd/2+.03],[1,2,.04]);
   if(facility){facility.exterior={at:[x,y,z+bd/2+.05],approach:[x,y,z+bd/2+1.4],normal:[0,0,1],angle:0};facility.inside='普通の仕事と、長く使われた石が同じ部屋にある。';facility.catInside='木と紙と、何度も戻ってきた人の匂いがある。';}
  }
  list.forEach((s,i)=>building(...s.center,...s.size,s.type==='bell'?11:s.type==='archive'?6:4.5,i,s));
  let n=0;for(const dx of [-29,-16,16,29])for(const dz of [-29,-15,15,29]){const x=cx+dx,z=cz+dz;if(list.some(s=>Math.abs(x-s.center[0])<s.size[0]/2+5&&Math.abs(z-s.center[1])<s.size[1]/2+5))continue;building(x,z,6+(n%2),5.6,3.2+(n%3)*.65,8+n++);}
  // Old walls, reused columns and arches cross daily routes rather than replacing them.
  for(const [dx,dz]of [[-12,-12],[12,13],[-11,26]]){deco.add('block',materials.old,[cx+dx,y+.6,cz+dz],[3,1.2,.6]);deco.add('block',materials.honey,[cx+dx-1,y+1.3,cz+dz],[.5,2.6,.5]);}
  const cpath=[[cx,y,cz],[cx,y,cz+9],[cx+9,y,cz+9],[cx+9,y,cz],[cx,y,cz]];wards[w.id].roads.push(cpath);localPaths['cv-square-'+w.id]=cpath;
  const bench=gatePiece(cx+7,y,cz+11,2,.42,.4,materials.wood,g);catSteps.push(bench);targets.push({id:'cv:view-'+w.id,kind:'quiet-view',verb:'眺める',label:w.name+'を眺める',text:'新しい屋根の下にも、古い壁と今日の暮らしが残っている。',object:bench,localPoint:[0,.3,0],range:2.8,profiles:['human','cat'],viewEye:[cx+7,y+3,cz+11],viewFocus:[cx,y+2,cz-12]});
  const count=capitalCatCounts[w.id];for(let k=0;k<count;k++){const dx=k%2?-12:12,dz=-20+k*7+(w.id==='canalWard'&&k===3?7:0),x=cx+dx,z=cz+dz;const arch=new THREE.Group();g.add(arch);gatePiece(x-.8,y,z,.14,.65,.3,materials.old,arch);gatePiece(x+.8,y,z,.14,.65,.3,materials.old,arch);const beam=box(x,y+.65,z,1.75,.14,.3,materials.old,arch);beam.castShadow=false;catRoutes.push({id:'cv-cat-'+w.id+'-'+k,ward:w.id,object:beam,start:[x,y,z-1],end:[x,y,z+1],center:[x,y,z],clearance:.65});
   if(k<capitalCatTexts[w.id].length){const marker=gatePiece(x+.2,y+.1,z+.6,.15,.08,.2,materials.old,g);targets.push({id:'cv:cat-'+w.id+'-'+k,kind:'inspect',label:'低い場所の気配',text:capitalCatTexts[w.id][k],object:marker,localPoint:[0,.08,0],range:1.8,profiles:['cat']});}const step=box(x+1.8,y,z+1,1,.32,.8,materials.old,g);step.castShadow=false;catSteps.push(step);
  }
  
  // Small daily landmarks distinguish the wards without additional lights.
  if(w.id==='lowerWard'){
   for(const dx of [-8,8]){deco.add('block',materials.wood,[cx+dx,y+.7,cz-9],[3,.18,1.4]);deco.add('block',materials.cloth,[cx+dx,y+2.4,cz-9],[3.5,.14,2]);for(const s of [-1,1])deco.add('block',materials.wood,[cx+dx+s*1.4,y+1.1,cz-9],[.12,2.2,.12]);}
   for(const dx of [-9,9]){deco.add('block',materials.wood,[cx+dx,y+.65,cz+17],[2,.22,1.3]);for(const a of [-1,1])for(const b of [-1,1])deco.add('block',materials.old,[cx+dx+a*.75,y+.4,cz+17+b*.65],[.22,.65,.16]);}
   deco.add('block',materials.old,[cx-5,y+.4,cz+5],[1.4,.8,1.4]);deco.add('block',materials.water,[cx-5,y+.82,cz+5],[.9,.025,.9]);
  }else if(w.id==='canalWard'){
   for(let i=0;i<9;i++)deco.add('block',i%3?materials.wood:materials.cloth,[cx-24+i*1.4,y+.3,cz+9],[.8,.6,.8]);
   deco.add('block',materials.wood,[cx+18,y+.12,cz+5.5],[10,.24,3]);
  }else if(w.id==='civicWard'){
   deco.add('block',materials.old,[cx-5,y+.5,cz-7],[2,1,2]);deco.add('block',materials.water,[cx-5,y+1.02,cz-7],[1.4,.025,1.4]);deco.add('block',materials.honey,[cx+6,y+1.6,cz-7],[.65,3.2,.65]);deco.add('block',materials.paper,[cx-8,y+1.2,cz+9],[2.4,1.6,.1]);
  }else if(w.id==='scholarHeights'){
   for(let i=0;i<7;i++)deco.add('block',materials.old,[cx-7+i*2,y+.18,cz-9],[.5,.36,.5]);deco.add('block',materials.honey,[cx+8,y+.6,cz-9],[1.2,1.2,1.2]);deco.add('block',materials.copper,[cx+8,y+1.3,cz-9],[1.7,.14,1.7]);
   deco.add('block',materials.old,[cx-23,y+5,cz-22],[3,10,3]);
  }else{
   deco.add('block',materials.old,[cx+5,y+.6,cz+6],[2,1.2,2]);deco.add('block',materials.wood,[cx+5,y+1.22,cz+6],[2,.12,2]);
   for(const dx of [-4,4])deco.add('block',materials.old,[cx+dx,y+1.4,cz-11],[1,2.8,1]);deco.add('block',materials.old,[cx,y+2.9,cz-11],[9,.6,1]);
  }
  for(const material of [materials.roof,materials.copper]){const items=wards[w.id].roofItems.filter(r=>r.material===material),mesh=new THREE.InstancedMesh(roofGeo,material,items.length),dummy=new THREE.Object3D();items.forEach((r,i)=>{dummy.position.fromArray(r.position);dummy.scale.fromArray(r.scale);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);});mesh.userData.walkSoft=true;g.add(mesh);}batch.finish();deco.finish();
 }
 // Canal crossing uses real supported strips; its banks remain dry and accessible.
 const canal=wards.canalWard,cy=8;gatePiece(-684,7.82,-320,64,.025,7.6,materials.water,canal.root);for(const z of [-324.2,-315.8])gatePiece(-684,7.4,z,66,.6,.65,materials.old,canal.root);strip([[-684,8,-332],[-684,8,-308]],5,materials.stone,canal.root);gatePiece(-659,8,-320,1.2,2.8,7.8,materials.old,canal.root);const sluice=gatePiece(-660,7.9,-320,.2,1.8,6.8,materials.wood,canal.root);canal.sluice=sluice;const reflection=gatePiece(-691,7.85,-320,1.3,.012,6.4,materials.old,canal.root);canal.reflection=reflection;
 // Short aqueduct, then ordinary streets; never a dominating palace.
 for(let i=0;i<7;i++){gatePiece(-657+i*4,8,-357,.7,7,.8,materials.honey);gatePiece(-657+i*4,14.7,-357,4,.5,1.4,materials.old);}const palace=gatePiece(-770,22,-487,20,8,15,materials.stone);gatePiece(-770,30,-487,23,1,18,materials.roof);palace.name='遠景の王宮（入場不可）';targets.push({id:'cv:palace',kind:'inspect',label:'遠くの王宮',text:'高台の向こうに屋根が見える。今日の通行路は、そちらへは続いていない。',object:palace,localPoint:[0,2,0],range:3,profiles:['human','cat']});
 for(const l of links){const o=gatePiece(...l.gate,5,1.2,.3,materials.wood);const a=l.points[1],b=l.points[2];o.rotation.y=-Math.atan2(b[2]-a[2],b[0]-a[0])+Math.PI/2;o.name='作業中の区画通路';gates.push({link:l,object:o});targets.push({id:'cv:route-'+l.from+'-'+l.to,kind:'inspect',label:'通路の作業札',text:'今は荷と作業が通る。宿の案内と、街の公告を確かめてみよう。',object:o,localPoint:[0,.5,0],range:3,profiles:['human','cat']});}
 for(const [id,ward,dx,dz,label,text]of capitalObservations){const w=wards[ward],[x,y,z]=w.center,o=gatePiece(x+dx,y,z+dz,.65,.12,.6,materials.paper,w.root);observationProps[id]=o;targets.push({id:'cv:'+id,kind:'inspect',label,text,object:o,localPoint:[0,.2,0],range:2.8,profiles:['human','cat'],ward});}
 for(const event of capitalEvents){const w=wards[event.ward],[x,y,z]=w.center,index=capitalEvents.filter(e=>e.ward===event.ward).indexOf(event),o=gatePiece(x-6-index*1.5,y,z-4,.65,.3,.65,materials.wood,w.root);eventProps.push({event,object:o});targets.push({id:event.id,kind:'capital-event',label:event.label,text:event.text,object:o,localPoint:[0,.4,0],range:2.6,profiles:['human','cat'],ward:event.ward,event});}
 // A low old drain offers the alternative cat route near the Civic junction.
 const oldEntry=gatePiece(-599,9.2,-422,.8,.12,.6,materials.old);targets.push({id:'cv:cat-old-entry',kind:'inspect',label:'壁横の古い排水路',text:'低い壁の向こうに、今の街路とは違う向きの通路がある。',object:oldEntry,localPoint:[0,.18,0],range:3.4,profiles:['cat'],ward:'civicWard'});
 for(const c of capitalCharacters){const w=wards[c.ward],[x,y,z]=w.center;const o=new THREE.Group();root.add(o);o.name=c.name;o.userData.community=true;o.userData.appearanceIndex=capitalCharacters.indexOf(c)+8;o.userData.visitorRole={activity:c.id==='cvGaren'?'rope':c.id==='cvVal'?'carrying':c.id==='cvOrm'?'tools':'conversation',prop:c.id==='cvGaren'?'rope':c.id==='cvVal'?'tools':c.id==='cvOrm'?'tools':null,hair:c.profile.hair,accent:0x849190};const body=new THREE.Mesh(new THREE.CylinderGeometry(.22*c.profile.width,.28*c.profile.width,1.02,8),materials.cloth);body.position.y=.68;const head=new THREE.Mesh(new THREE.SphereGeometry(.22,8,6),materials.skin);head.position.y=1.42;o.add(body,head);o.position.set(x+10,y,z+15);residentScale.normalize(o,{head});o.scale.y*=c.profile.height/1.75;actors[c.id]=o;people.push({object:o,character:c,ward:c.ward});
  const base=[x,y,z],work=[x+10+(capitalCharacters.filter(v=>v.ward===c.ward).indexOf(c))*2,y,z+15],home=[x-7-(capitalCharacters.filter(v=>v.ward===c.ward).indexOf(c))*2,y,z+15];localPaths['cv-work-'+c.id]=[base,[work[0],y,z],work];localPaths['cv-home-'+c.id]=[base,[home[0],y,z],home];const shop=shops.find(s=>s.id===c.mainLocation);localPaths[c.mainLocation]=[base,[base[0],y,shop.exterior.approach[2]],shop.exterior.approach];}
 // General citizens are scheduled locally; fewer in old streets, no permanent props.
 let gi=0;for(const w of W){const [x,y,z]=w.center;for(let i=0;i<w.population;i++){const o=new THREE.Group();root.add(o);o.name=w.name+'の住民 '+i;o.userData.community=true;o.userData.appearanceIndex=gi++;o.userData.visitorRole={activity:i%4===0?'carrying':i%4===1?'browsing':i%4===2?'resting':'conversation',prop:i%6===0?'parcel':null,hair:[0x5d5141,0x88785f,0xa5a092,0x3a3935][i%4],accent:0x879280};const body=new THREE.Mesh(new THREE.CylinderGeometry(.22,.3,1.02,6),i%2?materials.wood:materials.cloth);body.position.y=.68;const head=new THREE.Mesh(new THREE.SphereGeometry(.22,6,5),materials.skin);head.position.y=1.42;o.add(body,head);o.position.set(x+(i%6-2.5)*2.2,y,z+6+Math.floor(i/6)*2.1);residentScale.normalize(o,{head});people.push({object:o,ward:w.id,index:i});const home=o.position.toArray(),work=[x+(i%6-2.5)*2.2,y,z-5-Math.floor(i/6)*2.1];localPaths['cv-home-general-'+w.id+'-'+i]=[[x,y,z],home];localPaths['cv-work-general-'+w.id+'-'+i]=[[x,y,z],work];}}
 for(const s of shops){if(localPaths[s.id])continue;const w=wards[s.ward],base=w.center;localPaths[s.id]=[base,[base[0],base[1],s.exterior.approach[2]],s.exterior.approach];}
 localPaths['cv-val-finn']=[[-560,10,-430],[-568,10,-430],[-568,10,-438]];root.updateMatrixWorld(true);return{root,wards,actors,people,shops,targets,shells,catSteps,catRoutes,localPaths,grounds,gates,eventProps,observationProps,materials,royalRoad:capitalRoad,heightAt:capitalHeight,links,stats:{wards:W.length,major:capitalCharacters.length,general:W.reduce((a,w)=>a+w.population,0),interiors:shops.length,catRoutes:catRoutes.length}};
}
export function capitalRegions(stay){setCapitalState(stay.data);const regions=W.map(w=>{const [x,y,z]=w.center;return{id:wardId(w.id),parentRegion:'caer-veyra',name:'Caer Veyra · '+w.name,description:w.english+' — 古い構造と、今日の暮らしが重なる王都',conditional:true,visible:()=>!!stay.data.discoveries['cv:arrival']&&(w.id!=='oldQuarter'||capitalWardOpen(w.id)),enabled:()=>capitalWardOpen(w.id),disabledLabel:'通路を確認',entryPoint:w.entry,walkingBounds:{minX:x-w.size[0]/2,maxX:x+w.size[0]/2,minZ:z-w.size[1]/2,maxZ:z+w.size[1]/2},contains:p=>capitalWardAt(p.x,p.z)?.id===w.id,cameraPresets:[{id:'cv-'+w.id+'-overview',name:'全景',eye:[x+45,y+38,z+42],focus:[x,y+3,z]},...capitalFacilities.filter(s=>s.ward===w.id).map(s=>({id:s.id,name:s.name,eye:[x+s.offset[0]+8,y+10,z+s.offset[1]+14],focus:[x+s.offset[0],y+2,z+s.offset[1]]})),{id:'cv-'+w.id+'-square',name:'広場',eye:[x+12,y+8,z+16],focus:[x,y,z]},{id:'cv-'+w.id+'-sunset',name:'王都夕景',eye:[x+5,y+16,z+3],focus:[-644,15,-380]}],navigationTargets:[{id:'cv-square-'+w.id,name:w.name+'の広場',short:'広',position:w.center},...capitalFacilities.filter(s=>s.ward===w.id).map(s=>({id:s.id,name:s.name,short:s.name.slice(0,1),position:[x+s.offset[0],y,z+s.offset[1]+s.size[1]/2+1.4]})),...links.filter(l=>l.from===w.id||l.to===w.id).map(l=>{const next=l.from===w.id?l.to:l.from,v=W.find(w=>w.id===next);return{id:'cv-direction-'+next,name:v.name+'方面',short:'道',position:l.gate}})],mapBounds:{minX:x-w.size[0]/2,maxX:x+w.size[0]/2,minZ:z-w.size[1]/2,maxZ:z+w.size[1]/2},ambientProfile:w.ambient};});return[{id:'caer-veyra',name:'Caer Veyra',description:'Caer Veyra — 歴史が積み重なった王都',conditional:true,markOnEnter:false,visible:()=>!!stay.data.discoveries['mire:sign']||!!stay.data.discoveries['cv:arrival'],enabled:()=>capitalWardOpen('lowerWard'),entryPoint:W[0].entry,walkingBounds:{minX:-820,maxX:-480,minZ:-550,maxZ:-248},contains:p=>capitalHeight(p.x,p.z)!==null&&!capitalWardAt(p.x,p.z),cameraPresets:[{id:'cv-city-overview',name:'王都全景',eye:[-580,75,-270],focus:[-650,15,-380]},{id:'cv-city-gate',name:'外門',eye:[-549,17,-310],focus:[-578,10,-320]}],navigationTargets:[{id:'cv-gate',name:'王都外門',short:'門',position:W[0].entry},{id:'violet-mire',name:'Violet Mire方面',short:'湿',position:capitalRoad[0]}],mapBounds:{minX:-775,maxX:-525,minZ:-470,maxZ:-280},ambientProfile:'capital-market'},...regions];}
export function connectCapital({THREE,capital,stay,townLife,walking,inspections,dialogue,residentLife,residentDay,shopSystem,regions,namedTravel,ambientAudio,camera,getQuality}){
 let elapsed=0,busy=false,lastUnlock='',periodKey='',lastEncounter=null;const controllers=[],controllerById=new Map();
 const seen=id=>!!stay.data.discoveries[id];
 function remember(id,text,kind='place'){if(!seen(id)){stay.data.discoveries[id]={day:stay.data.currentDay,period:townLife.state.period,playerMode:walking.state.profile.id,label:text.slice(0,75)};stay.changed();}return stay.note(id,text,{kind,playerMode:walking.state.profile.id});}
 for(const e of capital.targets){const was=e.enabled;e.enabled=()=>!shopSystem.current&&(!e.ward||capitalWardOpen(e.ward))&&(!was||was())&&(e.kind!=='capital-event'||e.event.periods.includes(townLife.state.period));inspections.resolver.register(e);}

 for(const {object,character:c,ward,index:i}of capital.people){const record=residentLife.records.find(r=>r.object===object);const id=c?.id??'general-'+ward+'-'+i,home=c?'cv-home-'+c.id:'cv-home-general-'+ward+'-'+i,work=c?'cv-work-'+c.id:'cv-work-general-'+ward+'-'+i;const schedule=c?.schedule??{morning:work,day:ward==='civicWard'&&i<2?'cv-archive':work,evening:'cv-square-'+ward,night:'home'};const shelter=c?.mainLocation??'cv-square-'+ward;const e=residentDay.addScheduled(record,{id:'capital-'+id,regionId:wardId(ward),home,schedule,shelter,dawnPlace:shelter,chooseDestination:({day,period})=>c?.id==='cvVal'&&day%14===5&&['evening','night'].includes(period)?'cv-val-finn':null,present:()=>capitalWardOpen(ward)});controllers.push(e);if(c){controllerById.set(c.id,e);e.speed*=c.profile.age>60?.86:c.id==='cvSophia'?1.12:1;}}
 shopSystem.setCommunity({location:id=>{const c=controllerById.get(id);return c?(shopSystem.current?.shop.characterId===id?shopSystem.current.shop.id:c.inside??(c.visible?'town':'private')):null;},draw:id=>{const e=controllerById.get(id);if(!e)return false;const o=e.record.object;if(o.parent!==e.parent)e.parent.attach(o);o.position.copy(o.parent.worldToLocal(e.feet.clone().add(new THREE.Vector3(0,e.offset,0))));o.visible=e.visible&&!e.renderHidden&&camera.position.distanceTo(e.feet)<(getQuality()==='mobile'?65:95);return true;}});
 inspections.handlers.set('capital-event',e=>{const state=stay.data.events[e.id]??={state:'unseen'};state.state='noticed';state.noticedDay??=stay.data.currentDay;remember(e.id,e.text,'event');inspections.present(e,{text:e.text});});
 inspections.onPresent(({entry,text})=>{if(!entry.id.startsWith('cv:')&&!entry.id.startsWith('inside:cv-'))return;remember(entry.id,text??entry.text??entry.label,entry.profiles?.length===1&&entry.profiles[0]==='cat'?'cat':'place');const aliases={'inside:cv-records:ordinary':'cv:records-map','inside:cv-archive:catalog':'cv:archive-catalog','inside:cv-maps:catalog':'cv:old-map'};if(aliases[entry.id])remember(aliases[entry.id],text??entry.text);if(entry.id==='cv:cat-old-entry')sync();});
 const reactions={cvCedric:'通行帳の空白と、地図の空白は別だ。まず、どの頁だったかを確かめよう。',cvLeon:'またいるな。今日は門の裏でも見かけたぞ。',cvMira:'奥まで見てきたんだね。夕食はまだあるよ。足を休めてから話して。',cvGaren:'古い石組みはある。造った者の名は、管理表にはない。',cvSophia:'図にない水路でも、荷が通った記録は残ることがある。荷札からなら、探せるかもね。',cvEdras:'……この規模の地図で、ここだけ線が避けている。書かれていないことと、なかったことは、別です。',cvLyune:'目録だけが残った年代です。誰が抜いたかは、この棚からは分かりません。',cvCassian:'現在の区画境界とは合わない。それだけで、古い図が間違いとは言えません。',cvOrm:'鐘は回数より間隔だ。空洞の響きまで同じとは、まだ言えない。',cvSerena:'方向は近い。でも点の間隔は合わない。欠けた部分まで、揃えて考えてはいけません。',cvYulio:'この線の曲がり方、今の旧区画にも残っています。地図の方だけが途切れている。',cvNoah:'前にも、これを並べた人がいたんですね。どこまで確かめたのか、読めたらいいのに。',cvElda:'昔は水門の名も違ったよ。私には、その呼び名の方が分かる。',cvVal:'欠けた記録で、石まで新しくはならん。'};
 for(const c of dialogue.characters.filter(c=>capitalCharacters.some(p=>p.id===c.id))){const previous=c.eventReply;c.eventReply=args=>{if(c.id==='cvVal'&&seen('cv:finn-val'))return args.index%2===1?'誰の話だ。':previous?.(args);if(c.id==='cvElda'&&seen('cv:finn-visit')&&stay.data.currentDay>(stay.data.discoveries['cv:finn-visit']?.day??99999))return '昔、ああいう色の外套を着た子がいたねえ。誰の家の子だったか。';if(args.profile==='cat'&&c.id==='cvLeon'&&(stay.data.memories[c.id]?.cat?.visits??0)>1)return reactions.cvLeon;return seen('cv:archive-catalog')&&args.index%2===1?reactions[c.id]:previous?.(args);};c.calendarReply=({index})=>index%3===2?(townLife.state.weather==='rain'?'今日は石が濡れている。作業は軒の内側で続けるよ。':townLife.state.weather==='blackout'?'宿と門の小灯りは残っている。狭い道では、ゆっくり歩いて。':townLife.state.period==='night'?'今は少し静かだね。朝になれば、また同じ仕事が始まる。':null):null;}
 dialogue.onSpeak(({character:c,profile,text})=>{if(profile!=='human')return;if(c.id==='cvCedric')remember('cv:gate','通行所で、普通の旅人として名前を記した。','person');if(c.id==='cvMira')remember('cv:guide','宿の主人に、水門と公告の場所を聞いた。','person');if(c.id==='cvGaren'||c.id==='cvSophia')remember('cv:canal-ledger','水路の荷と水位の、普通の日課を聞いた。','person');if(c.id==='cvEdras'||c.id==='cvLyune')remember('cv:scholar-intro','古い図の向きは、高台でも確かめられるらしい。','person');if(c.id==='cvYulio')remember('cv:old-map','地図師は、現在図にない古い街路を指した。','person');if(c.id==='cvElda')remember('cv:elda-direction','鐘のない鐘楼の方。古い呼び名が、道の手掛かりになった。','person');if(c.id==='cvVal'&&seen('cv:finn-val'))remember('cv:val-after','フィンのことを聞いても、修繕師は「誰の話だ」とだけ言った。','person');});
 for(const [id,text]of [['greenBard','大きな街ほど、古い道が上手に隠れるんだ。毎日の足音の下にね。'],['starmaker','王都の観測なら、方向と時刻を比べられるでしょう。図の空白まで同じとは、まだ言えません。'],['bookseller','目録が残っているなら、読んだ人はいたのでしょう。本文の行方は、別に調べなくては。']]){const c=dialogue.characters.find(c=>c.id===id),old=c.eventReply;c.eventReply=args=>seen('cv:archive-catalog')&&args.index%4===2?text:old?.(args);}
 const encounter=capital.observationProps['stone-fragment'];inspections.resolver.register({id:'cv:finn-val-scene',kind:'capital-encounter',verb:'様子を見る',label:'工房前の短い会話',object:encounter,localPoint:[0,.4,0],range:4,profiles:['human','cat'],enabled:()=>!shopSystem.current&&!!namedTravel.controllers.get('greenBard')?.externalVisit&&capitalWardOpen('oldQuarter')&&controllerById.get('cvVal')?.visible&&controllerById.get('cvVal').feet.distanceTo(namedTravel.controllers.get('greenBard').feet)<5});inspections.handlers.set('capital-encounter',e=>{remember('cv:finn-val','ヴァルは外套を見て、「まだ使っているのか」と言った。フィンは「丈夫なんだ」と答えた。','person');inspections.present(e,{text:'ヴァル「……その外套、まだ使っているのか。」\nフィン「丈夫なんだ。」\nヴァル「そうか。」'});});
 for(const w of W)ambientAudio.zones.push({id:'cv-'+w.id,area:'town',sourceId:w.id==='canalWard'?'lake-water':w.id==='scholarHeights'?'nine-wind':null,position:w.center,radius:45,gain:w.id==='canalWard'?.04:.015,src:null});
 function sync(){if(busy)return;busy=true;try{setCapitalState(stay.data);extendRoyalRoad(capitalWardOpen('lowerWard'));const key=W.map(w=>capitalWardOpen(w.id)).join(':');if(key!==lastUnlock){lastUnlock=key;residentDay.refreshSchedules(e=>e.community?.regionId?.startsWith('caer-'));regions.refresh();}for(const g of capital.gates)g.object.visible=!capitalWardOpen(g.link.to);for(const e of shopSystem.entrances.filter(e=>e.shop.id.startsWith('cv-'))){e.enabled=()=>!shopSystem.current&&capitalWardOpen(e.shop.ward);const registered=inspections.resolver.entries.get(e.id);if(registered)registered.enabled=e.enabled;}const t=stay.data.threads.caerVeyraRecords??={stage:'unseen'};t.stage=seen('cv:old-number')&&seen('cv:archive-catalog')?'compared':seen('cv:records-map')&&seen('cv:archive-catalog')?'missing':seen('region:caer-canalWard')?'ordinary':seen('cv:arrival')?'arrival':'unseen';}finally{busy=false;}}
 stay.onChange(sync);townLife.onChange(sync);sync();
 function update(dt){elapsed+=dt;if(elapsed<.25)return;const step=elapsed;elapsed=0;sync();const p=walking.state.feet;if(walking.active&&!shopSystem.current&&capitalHeight(p.x,p.z)!==null&&p.x<-564&&!seen('cv:arrival')){remember('cv:arrival','古い門をくぐって、Caer Veyraへ着いた。通行所では、今日の旅人の名を記していた。');remember('region:caer-veyra','歴史の重なる王都にも、朝食と荷の支度があった。');sync();}if(seen('cv:records-map')&&seen('cv:archive-catalog')){remember('cv:comparison','前にも観察し、比べ、記した人がいた。その記録の一部だけが、今は欠けている。');}
  const current=regions.current.id,quality=getQuality(),time=townLife.state,night=time.period==='night'||time.weather==='night',wet=time.weather==='rain',dark=time.weather==='blackout';const k=[time.period,time.weather,time.season].join(':');if(periodKey!==k){periodKey=k;capital.materials.stone.color.setHex(wet?0x929fa2:time.period==='evening'?0xd8c29c:0xc6c0a7);capital.materials.honey.color.setHex(wet?0x9aa39d:time.period==='evening'?0xe1b37b:0xcdb990);capital.materials.old.color.setHex(wet?0x596967:0x787d76);capital.materials.grass.color.setHex(time.season==='autumn'?0x817f61:0x7d866b);capital.materials.glow.emissiveIntensity=dark?.01:night?.7:.05;capital.materials.oil.emissiveIntensity=dark?.8:night?.5:.08;capital.materials.water.color.setHex(wet?0x3e565f:time.period==='evening'?0x5d6e70:0x4a656c);}
  for(const w of W){const a=capital.wards[w.id],budget=regionActivity(current,wardId(w.id),quality),distance=Math.hypot(camera.position.x-w.center[0],camera.position.z-w.center[2]);a.detail.visible=budget.details||distance<45;for(const o of a.windowGroups)o.visible=!night||o.userData.windowIndex%3!==1;for(const e of controllers.filter(e=>e.community.regionId===wardId(w.id))){const far=distance>100&&!shopSystem.current;e.record.object.userData.regionDormant=budget.activity==='dormant';e.renderHidden=far&&budget.activity!=='active';if(e.renderHidden)e.record.object.visible=false;}}
  capital.wards.canalWard.sluice.position.y=7.9+(time.period==='morning'?.35:0);capital.wards.canalWard.reflection.visible=time.period==='evening'||wet;capital.wards.canalWard.reflection.material=capital.materials.water;
  const finnDay=seen('region:caer-oldQuarter')&&time.dayIndex%14===5&&['evening','night'].includes(time.period)&&!['rain','blackout'].includes(time.weather);const finnPoint=[-566,10,-438];namedTravel.setExternalVisit?.('greenBard',finnDay?{id:'capital-old',point:finnPoint,region:'caer-oldQuarter'}:null);const finn=namedTravel.controllers.get('greenBard');if(finn?.externalVisit){finn.actor.userData.activityRegion='caer-oldQuarter';if(walking.active&&p.distanceTo(finn.feet)<6)remember('cv:finn-visit','旧区画で、緑の外套の旅人を見かけた。','person');}
 }
 return{controllers,remember,sync,update,get stats(){return{major:controllerById.size,general:controllers.length-controllerById.size,active:controllers.filter(e=>e.visible&&regionActivity(regions.current.id,e.community.regionId,getQuality()).activity==='active').length,wards:W.map(w=>({id:w.id,...regionActivity(regions.current.id,wardId(w.id),getQuality()),open:capitalWardOpen(w.id)}))};}};
}
