import {lunmereLayout as layout,lunmereShops,lunmereCharacters,lakeTownEvents} from './lunmere-data.js';
import {buildLunmereInterior} from './lunmere-interiors.js';
export function lunmereHeight(x,z){
 if(x>=-465&&x<=-397&&z>=-3&&z<=55)return 6.16;
 for(let i=1;i<layout.road.length;i++){const a=layout.road[i-1],b=layout.road[i],dx=b[0]-a[0],dz=b[2]-a[2],t=Math.max(0,Math.min(1,((x-a[0])*dx+(z-a[2])*dz)/(dx*dx+dz*dz)));if(Math.hypot(x-a[0]-t*dx,z-a[2]-t*dz)<3.5)return a[1]+t*(b[1]-a[1]);}return null;
}
export function buildLunmere({THREE,scene,box,residentScale,lake}){
 const root=new THREE.Group();root.name='Lunmere lakeside town';scene.add(root);const materials={},floors=[],catSteps=[],targets=[],sources=[],shells=[],people=[],actors={},windows=[],details=[];
 const mat=(id,color)=>materials[id]=new THREE.MeshStandardMaterial({color,roughness:1});const grass=mat('grass',0x727f65),stone=mat('stone',0x9c9d8d),wood=mat('wood',0x74614c),wall=mat('wall',0xd5d8cc),roof=mat('roof',0x607d73),wet=mat('wet',0x6c7366),cloth=mat('cloth',0xa8aea1),water=mat('water',0x55767a);water.metalness=.015;water.roughness=.88;
 const roofGeo=new THREE.BufferGeometry();roofGeo.setAttribute('position',new THREE.Float32BufferAttribute([-.5,0,-.5,.5,0,-.5,0,1,-.5,-.5,0,.5,.5,0,.5,0,1,.5],3));roofGeo.setIndex([0,2,1,3,4,5,0,3,5,0,5,2,1,2,5,1,5,4,0,1,4,0,4,3]);roofGeo.computeVertexNormals();
 const glow=new THREE.MeshStandardMaterial({color:0xe3c791,roughness:1,emissive:0xffb86b,emissiveIntensity:.25});materials.glow=glow;
 const piece=(x,y,z,w,h,d,m,soft=false)=>{const o=box(x,y,z,w,h,d,m,root);o.userData.walkSoft=soft;return o;};
 function strip(points,width,m){const positions=[],indices=[];for(let i=0;i<points.length;i++){const a=points[Math.max(0,i-1)],b=points[Math.min(points.length-1,i+1)],len=Math.hypot(b[0]-a[0],b[2]-a[2]),nx=-(b[2]-a[2])/len*width/2,nz=(b[0]-a[0])/len*width/2,p=points[i];positions.push(p[0]+nx,p[1],p[2]+nz,p[0]-nx,p[1],p[2]-nz);if(i)indices.push(i*2-2,i*2,i*2-1,i*2-1,i*2,i*2+1);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setIndex(indices);g.computeVertexNormals();const o=new THREE.Mesh(g,m);o.userData.walkSoft=true;root.add(o);return o;}
 strip(layout.road,7,grass);strip(layout.road.map(p=>[p[0],p[1]+.005,p[2]]),2.5,stone);
 const land=piece(-431,3.9,26,68,2.26,58,grass,true);floors.push(land);const inlet=piece(-421,5.76,-13,98,.02,22,water,true);
 // A short supported bridge crosses a damp hollow, retaining the same route elevation.
 const bridge=piece(-360,5.97,14,5.5,.16,2.7,wood);bridge.userData.walkFloor=true;bridge.userData.walkSoft=true;floors.push(bridge);for(const x of [-362,-358])for(const z of [12.8,15.2])piece(x,3.9,z,.16,2.23,.16,wood,true);
 const shops=lunmereShops.map(s=>({...s,craftTemplate:s.type==='workshop'?lake.boat:null,buildInterior:buildLunmereInterior}));
 function building(x,z,w,d,h,index){const shell=piece(x,6.16,z,w,h,d,wall);shell.name=index<4?shops[index].name:'湖畔の住宅 '+(index-3);shells.push({object:shell,b:new THREE.Box3().setFromObject(shell,true)});const cap=new THREE.Mesh(roofGeo,roof);cap.position.set(x,6.16+h,z);cap.scale.set(w+.55,.95,d+.55);cap.userData.walkSoft=true;root.add(cap);for(const dx of [-w*.25,w*.25]){const win=piece(x+dx,7.5,z+d/2+.03,.54,.64,.04,glow,true);windows.push(win);}piece(x,6.16,z+d/2+.025,.85,1.9,.06,wood,true);piece(x,8.18,z+d/2+.3,1.25,.09,.65,wood,true);return shell;}
 for(let i=0;i<shops.length;i++){const s=shops[i],[x,z]=s.center,[w,d]=s.size;building(x,z,w,d,3.4,i);s.exterior={at:[x,6.16,z+d/2+.05],approach:[x,6.16,z+d/2+1.4],angle:0,normal:[0,0,1]};}
 for(const s of shops.filter(s=>['dining','supplies'].includes(s.type))){const [x,z]=s.center;piece(x,8.45,z+s.size[1]/2+.35,2.3,.07,.8,cloth,true);}
 layout.houses.forEach(([x,z],i)=>building(x,z,4.4+(i%2)*.5,4.3,2.8+(i%3)*.2,i+4));
 for(const [i,name]of [[0,'岸辺の住まい'],[1,'木窓の住まい']]){const [x,z]=layout.houses[i];shops.push({id:'lun-house-'+i,name,center:[x,z],size:[4.4,4.3],type:'residential',hours:{morning:'open',day:'open',evening:'open',night:'closed'},buildInterior:buildLunmereInterior,exterior:{at:[x,6.16,z+2.2],approach:[x,6.16,z+3.55],angle:0,normal:[0,0,1]}});}
 const pier=piece(-418,6,-4.4,2.4,.16,5.2,wood);pier.userData.walkFloor=true;floors.push(pier);for(const x of [-419,-417])for(const z of [-2.5,-6.5])piece(x,3.9,z,.16,2.1,.16,wet,true);
 const skiff=lake.boat.clone();skiff.name='Lunmereの係留舟';skiff.position.set(-420,5.88,-6);skiff.scale.setScalar(.8);skiff.traverse(o=>o.userData.walkSoft=true);root.add(skiff);const mooring=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-419,6.16,-5),new THREE.Vector3(-419.7,5.99,-5.8)]),new THREE.LineBasicMaterial({color:0x827969}));root.add(mooring);
 const bench=piece(-435,6.16,18,1.9,.43,.38,wood);catSteps.push(bench);
 const rock=piece(-403,6.16,16,1.4,.36,.85,stone);catSteps.push(rock);
 // Low foliage is instanced, with no per-blade animation or new light.
 const leaves=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,0),grass,40),m=new THREE.Matrix4();for(let i=0;i<40;i++){const x=i<24?-402-(i%8)*7.4:-410-(i%4)*11,z=i<24?45+Math.floor(i/8)*3:8+Math.floor((i-24)/4)*9; m.compose(new THREE.Vector3(x,6.2,z),new THREE.Quaternion(),new THREE.Vector3(.65,.28,.5));leaves.setMatrixAt(i,m);}leaves.userData.walkSoft=true;root.add(leaves);
 for(const [x,z]of [[-396,24],[-398,8],[-416,54],[-440,54],[-460,51],[-461,0],[-350,19],[-331,17]]){piece(x,lunmereHeight(x,z)??6.1,z,.25,2.1,.25,wood,true);const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(1.55,0),grass);crown.position.set(x,(lunmereHeight(x,z)??6.1)+3,z);root.add(crown);crown.userData.walkSoft=true;}
 const notice=(id,label,text,o,profiles=['human','cat'],kind='inspect')=>{const e={id,kind,label,text,object:o,localPoint:[0,.35,0],profiles,range:2.8};targets.push(e);return e;};
 const source=(id,label,p,w=.45,h=.25,d=.35)=>{const o=piece(...p,w,h,d,wood,true);o.name=label;if(id==='lun:water-mark')o.material=stone;sources.push({id,object:o,localPoint:[0,h+.05,0]});return o;};
 source('lake:parcel','湖畔の小包',[-308,6.04,-13]);source('lake:knot','舟の結び目',[-315,6.04,-24],.14,.07,.14);source('lake:morning-wood','朝の木片',[-312,6.04,-42],.65,.035,.13);
 source('lun:repair','修理中の舟',[-408,6.16,3],1.7,.35,.75);source('lun:net','乾かない網',[-409,7.2,5],1.5,.6,.025);source('lun:bag','宿の忘れ物',[-416.8,6.16,40]);source('lun:goods','空の商店籠',[-438.5,6.16,35.7]);source('lun:water-mark','岸の円',[-432,6.16,-2],.6,.055,.45);
 const reeds=piece(-433.4,6.16,-2,.35,.30,.5,grass,true);notice('lun:cat-circle','草の下の石片','草の下に、小さな丸い石片がある。縁の浅い傷には、水の匂いが残る。',reeds,['cat']);
 const fish=piece(-407,6.16,1,.45,.25,.4,wood,true);notice('lun:cat-fish','舟小屋の魚籠','魚と濡れた縄の匂いが、籠の底に残っている。細い古い紐が一本、木の隙間に挟まっている。',fish,['cat']);catSteps.push(fish);
 // Visible low crosspieces distinguish dry cat passages from the open human path.
 const catRoutes=[];for(const [id,x,z]of [['shed',-408,6],['inn',-417,32],['reeds',-432,-1]]){for(const dx of [-.75,.75])piece(x+dx,6.16,z,.08,.68,.12,wood);const beam=piece(x,6.16+.68,z,1.6,.12,.22,wood);catRoutes.push({id:'lun-'+id,label:'湖畔の低い抜け道',start:[x,6.16,z-1],end:[x,6.16,z+1],center:[x,6.16,z],clearance:.68,object:beam});}
 for(const [id,p,focus,label,text]of [['lun:view-town',[-399,6.16,13],[-432,7,15],'湖と町を眺める','木立の間に、小さな屋根と湖が並んでいる。'],['lun:view-water',[-418,6.16,-2],[-422,5.8,-16],'湖岸で眺める','町の音が少し遠のく。岸の杭だけが、水のそばに残る。']]){const o=piece(p[0],p[1],p[2],.5,.08,.45,stone,true);targets.push({id,kind:'quiet-view',verb:'眺める',label,text,object:o,localPoint:[0,.1,0],profiles:['human','cat'],range:2.5,viewEye:[p[0],p[1]+1.55,p[2]],viewFocus:focus});}
 const coatColors=[0x7a8580,0x777061,0x657983,0x889078],skin=mat('skin',0xb88e71),bodyGeo=new THREE.CylinderGeometry(.24,.34,1.05,8),headGeo=new THREE.SphereGeometry(.23,8,6);
 const coats=coatColors.map((c,i)=>mat('coat'+i,c));
 for(let i=0;i<14;i++){const o=new THREE.Group();root.add(o);const body=new THREE.Mesh(bodyGeo,coats[i%4]);body.position.y=.65;const head=new THREE.Mesh(headGeo,skin);head.position.y=1.42;o.add(body,head);o.userData.community=true;o.userData.appearanceIndex=i;o.userData.visitorRole={activity:['resting','rope','browsing','conversation','browsing','rope'][i%6],posture:['relaxed','working','thoughtful','listening'][i%4],prop:i===1||i===5?'rope':i===3||i===9?'parcel':i===0||i===7?'basket':null,hair:[0x514f43,0x6b5c49,0x8a8173,0x423e37][i%4],accent:0x839384};const p=[-401-i*1.2,6.16,22];o.position.fromArray(p);residentScale.normalize(o,{head});o.name=lunmereCharacters[i]?.name??'Lunmereの住民 '+(i+1);people.push({object:o,index:i});if(i<3)actors[lunmereCharacters[i].id]=o;}
 const localPaths={};const center=[-430,6.16,22];const approaches=Object.fromEntries(shops.map(s=>[s.id,s.exterior.approach]));
 localPaths['lun-finn']=[[-347,6.12,13],[-373,6.16,15],[-392,6.16,20],[-408,6.16,20],[-418,6.16,20],[-418,6.16,9],[-418,6.16,1]];
 localPaths['lun-square']=[center,[-429,6.16,23.5]];localPaths['lun-shore']=[center,[-430,6.16,12],[-432,6.16,12],[-432,6.16,-2]];localPaths['lun-pier']=[center,[-418,6.16,22],[-418,6.16,9],[-418,6.16,-2]];
 for(const s of shops){const p=approaches[s.id];localPaths[s.id]=s.id==='lun-inn'?[center,[-415,6.16,22],[-415,6.16,p[2]],p]:s.id==='lun-store'?[center,[-437,6.16,22],[-437,6.16,p[2]],p]:[center,[p[0],6.16,22],p];}
 const workIds=['lun-inn','lun-boats','lun-store','lun-store','lun-diner','lun-pier'];
 for(let i=0;i<14;i++){const path=localPaths[workIds[i%6]],p=path.at(-1),x=p[0]+([3,5].includes(i%6)?-1.5:1.5),z=p[2]+3+Math.floor(i/6)*1.7;localPaths['lun-home-'+i]=[...path,[x,6.16,z]];}
 for(const path of Object.entries(localPaths).filter(([id])=>['lun-square','lun-shore','lun-pier','lun-inn','lun-diner','lun-boats','lun-store'].includes(id)).map(([,path])=>path))strip(path.map(p=>[p[0],p[1]+.007,p[2]]),1.4,stone);
 const oil=glow.clone();oil.userData.blackoutBackup=true;materials.oil=oil;
 for(const [x,z]of [[-402,19],[-430,20],[-418,8]]){piece(x,6.16,z,.10,1.1,.10,wood,true);const lamp=piece(x,7.26,z,.18,.25,.18,oil,true);lamp.name='湖畔の小さな油灯';}
 localPaths['lake-rest']=[center,[-408,6.16,20],...layout.road.slice().reverse().slice(1,-1),[-309,6.04,-13]];
localPaths['lake-rest-alt']=[...localPaths['lake-rest'].slice(0,-1),[-311,6.04,-13]];
 return {root,skiff,mooring,pier,materials,windows,details,floors,catSteps,catRoutes,targets,sources,shells,people,actors,shops,localPaths,roadPoints:layout.road,heightAt:lunmereHeight,water:inlet,layout};
}
export function connectLunmere({THREE,lunmere,residentLife,residentDay,walking,inspections,shopSystem,townLife,stay,dialogue,ambientAudio,townEvents}){
 const controllers=[];for(const {object,index:i}of lunmere.people){const record=residentLife.records.find(r=>r.object===object),work=['lun-inn','lun-boats','lun-store','lun-store','lun-diner','lun-pier'][i%6];const schedule={morning:work,day:i===1?'lake-rest':i===9?'lake-rest-alt':i%3?'lun-square':work,evening:i<6?'lun-diner':'home',night:i===0?'lun-inn':i<3?work:'home'};const c=residentDay.addScheduled(record,{id:'lun-person-'+i,home:'lun-home-'+i,schedule,dawnPlace:i<3?work:(i%2?'lun-diner':'lun-inn'),shelter:i%2?'lun-diner':'lun-inn'});controllers.push(c);}
 const location=id=>{const i=lunmereCharacters.findIndex(c=>c.id===id);return i<0?null:controllers[i].inside??(controllers[i].visible?'town':'private');};shopSystem.setCommunity({location,draw:id=>{const i=lunmereCharacters.findIndex(c=>c.id===id);if(i<0)return false;const c=controllers[i],o=c.record.object;if(o.parent!==c.parent)c.parent.attach(o);o.position.copy(o.parent.worldToLocal(c.feet.clone().add(new THREE.Vector3(0,c.offset,0))));o.visible=c.visible;return true;}});
 for(const target of lunmere.targets){const enabled=target.enabled;target.enabled=()=>!shopSystem.current&&(!enabled||enabled());inspections.resolver.register(target);}
 inspections.onPresent(({entry})=>{if(!entry.id.startsWith('lun:')&&!entry.id.startsWith('event:lake-')&&!entry.id.startsWith('event:lun-'))return;const mode=walking.state.profile.id;if(!stay.data.discoveries[entry.id]){stay.data.discoveries[entry.id]={day:townLife.state.dayIndex,period:townLife.state.period,playerMode:mode,label:entry.label};stay.changed();}if(entry.text)stay.note(entry.id,entry.text,{kind:mode==='cat'?'cat':'place',playerMode:mode});else if(entry.event)stay.note(entry.id,entry.event.text,{kind:'event',playerMode:mode});});
 for(const c of dialogue.characters.filter(c=>lunmereCharacters.some(d=>d.id===c.id)))c.calendarReply=({profile,index})=>profile==='human'&&index%3===1?(townLife.state.weather==='rain'?'今日は板が滑るよ。桟橋ではゆっくり歩いて。':townLife.state.weather==='blackout'?'宿と食堂の小灯りは残してある。帰り道は、岸から少し離れて。':townLife.state.weather==='dawn'?'まだ湖が青いね。朝の支度が済むまで、少し待っていて。':townLife.state.dayIndex>1?'また湖の道を歩いてきたんだね。今朝は岸の石がひとつ多く見えたよ。':null):null;
 ambientAudio.zones.push({id:'lunmere-shore',sourceId:'lake-water',area:'town',kind:'harbor-water',position:[-425,6,-7],radius:35,gain:.10,source:null},{id:'lunmere-pier',area:'town',kind:'wood',position:[-418,6,-4],radius:8,gain:.05,source:null});
 shopSystem.onRoom(room=>{if(room.shop.id.startsWith('lun-'))ambientAudio.zones.push({id:room.shop.id+'-water',sourceId:'lake-water',area:room.shop.id,position:[0,.2,-1],radius:12,gain:.035,src:null});});
 const props=lunmere.sources;function apply(){const s=townLife.state,wet=s.weather==='rain',night=s.period==='night'||s.weather==='night',black=s.weather==='blackout';lunmere.materials.wood.color.setHex(wet?0x5b5348:0x74614c);lunmere.materials.grass.color.setHex(wet?0x5e7065:s.season==='autumn'?0x828064:0x727f65);lunmere.materials.cloth.color.setHex(s.season==='autumn'?0xa6967d:0xa8aea1);lunmere.materials.water.color.setHex(wet?0x486267:s.weather==='dawn'?0x647f89:night?0x354f5b:s.period==='evening'?0x697c78:0x55767a);lunmere.materials.glow.emissiveIntensity=black?.015:night?.75:.15;lunmere.materials.oil.emissiveIntensity=black?1.2:night?.7:.2;lunmere.windows.forEach((o,i)=>o.visible=!night||i%3!==1);for(const p of props){const event=lakeTownEvents.find(e=>e.source===p.id),state=townEvents.states.get(event?.id);if(['lake:parcel','lun:bag'].includes(p.id))p.object.visible=state?.state!=='resolved';}if(stay.data.discoveries['region:lunmere'])stay.note('lunmere-arrival','湖の道の先に、Lunmereの小さな屋根が並んでいた。');}
 townLife.onChange(apply);stay.onChange(()=>{if(stay.data.discoveries['region:lunmere']&&!stay.data.journal.some(n=>n.id==='lunmere-arrival'))stay.note('lunmere-arrival','湖の道の先に、Lunmereの小さな屋根が並んでいた。');});apply();return {controllers,location,apply,get stats(){return {residents:controllers.length,moving:controllers.filter(c=>c.currentState==='walking').length,lakeVisitors:controllers.filter(c=>c.visible&&c.feet.x>-397).length}}};
}
