import {streetDetour} from './street-detour.js';
// Bran and Finn share the already-tested resident street graph. Time changes
// request a destination; feet move through validated substeps, never teleport.
export function createNamedTravel({THREE,walking,shopSystem,residentDay,dialogue,townLife,getQuality=()=>'standard'}){
 const controllers=new Map(),{nodes,paths,route}=residentDay;
 function groundActor(actor,y){actor.updateWorldMatrix(true,true);actor.position.y+=y-new THREE.Box3().setFromObject(actor,true).min.y;}
 const targetNode=place=>paths[place==='square'?'square':place==='waterfront'?'mill':place==='harbor'?'harbor':place]?.at(-1);
 function clear(from,to,actor){let y=from.y;const length=Math.hypot(to.x-from.x,to.z-from.z),n=Math.max(1,Math.ceil(length/.07));for(let i=1;i<=n;i++){const p=from.clone().lerp(to,i/n),floor=walking.canStandTownAs('human',p.x,p.z,y,actor);if(floor===null)return false;y=floor;}return Math.abs(y-to.y)<.4;}
 function connect(feet,actor){const ordered=nodes.map((node,i)=>({i,d:node.point.distanceTo(feet)})).sort((a,b)=>a.d-b.d);for(const {i,d}of ordered){if(d>8)break;if(clear(feet,nodes[i].point,actor))return {node:i,points:[]};}
  return null;
 }

 for(const id of ['boatworker','greenBard']){const actor=dialogue.entries.find(e=>e.character.id===id).object;if(id==='greenBard'){const anchor=shopSystem.initialAnchor('square');if(anchor){actor.position.copy(actor.parent.worldToLocal(anchor));groundActor(actor,anchor.y);}}actor.updateWorldMatrix(true,true);const p=actor.getWorldPosition(new THREE.Vector3()),bottom=new THREE.Box3().setFromObject(actor,true).min.y;const feet=new THREE.Vector3(p.x,bottom,p.z);let node=connect(feet,actor);if(node===null&&id==='boatworker'){const nearest=nodes.map((n,i)=>({i,d:n.point.distanceTo(feet)})).sort((a,b)=>a.d-b.d);outer:for(const n of nearest){if(n.d>7)break;const at=nodes[n.i].point;for(const distance of [.7,.9])for(let angle=0;angle<8;angle++){const q=at.clone().add(new THREE.Vector3(Math.sin(angle*Math.PI/4)*distance,0,Math.cos(angle*Math.PI/4)*distance)),y=walking.canStandTownAs('human',q.x,q.z,q.y,actor);if(y===null||Math.abs(y-at.y)>.04)continue;q.y=y;if(nodes.some(n=>Math.abs(n.point.y-y)<.5&&Math.hypot(n.point.x-q.x,n.point.z-q.z)<.58)||!clear(q,at,actor))continue;feet.copy(q);actor.position.copy(actor.parent.worldToLocal(q.clone()));groundActor(actor,y);p.copy(actor.getWorldPosition(new THREE.Vector3()));node={node:n.i,points:[]};break outer;}}}if(node===null)continue;controllers.set(id,{id,actor,parent:actor.parent,feet,offset:p.y-feet.y,node:node.node,home:node.node,homeFeet:feet.clone(),connector:node.points,path:[],cursor:0,place:shopSystem.locationFor(id),destination:shopSystem.locationFor(id),speed:id==='boatworker'?.91:1.02,elapsed:0,currentState:'resting'});}
 for(const c of controllers.values()){if(['inn','tavern','waterfront'].includes(c.place)){const goal=targetNode(c.place);if(goal!==undefined){c.node=goal;c.feet.copy(nodes[goal].point);c.currentState=c.place==='waterfront'?'resting':'inside';}}}
 function request(){for(const c of controllers.values()){const place=shopSystem.locationFor(c.id);if(place===c.destination)continue;const home=place==='harbor'||place==='square';const goal=home?c.home:targetNode(place);if(goal===undefined)continue;c.destination=place;c.path=[...c.connector,c.node,...route(c.node,goal),...(home?[c.homeFeet.clone()]:[])];c.connector=[];c.cursor=0;c.currentState='departing';c.routePause=0;c.departureWait=c.id==='boatworker'?2.5:3.5;}}
 townLife.onChange(request);
 function advanceHidden(c,seconds){let budget=c.speed*seconds;for(let segmentCount=0;budget>1e-6&&c.cursor<c.path.length&&segmentCount<30;segmentCount++){const segment=c.path[c.cursor],target=typeof segment==='number'?nodes[segment].point:segment,delta=target.clone().sub(c.feet),d=Math.hypot(delta.x,delta.z);if(d<.015){if(typeof segment==='number')c.node=segment;c.cursor++;continue;}const move=Math.min(d,budget),n=Math.max(1,Math.ceil(move/.06));let moved=0;for(let j=0;j<n;j++){const x=c.feet.x+delta.x/d*move/n,z=c.feet.z+delta.z/d*move/n,y=walking.canStandTownAs('human',x,z,c.feet.y,c.actor);if(y===null)break;c.feet.set(x,y,z);moved+=move/n;}budget-=moved;c.actor.userData.travelYaw=Math.atan2(delta.x,delta.z);if(moved<move-1e-6)break;}if(c.cursor===c.path.length){c.place=c.destination;c.currentState=['inn','tavern'].includes(c.place)?'inside':'resting';}}
 function update(dt){for(const c of controllers.values()){c.elapsed+=Math.min(.1,Math.max(0,dt));const rate=shopSystem.current?.5:getQuality()==='mobile'&&walking.active&&walking.state.feet.distanceTo(c.feet)>30?.25:0;if(c.elapsed<rate)continue;const step=Math.min(.5,c.elapsed);c.elapsed=0;
  if(c.currentState==='departing'){c.departureWait-=step;if(c.departureWait>0)continue;if(walking.canStandTownAs('human',c.feet.x,c.feet.z,c.feet.y,c.actor)===null){let exit=false;for(let i=c.cursor+1;i<Math.min(c.cursor+10,c.path.length);i++){const p=typeof c.path[i]==='number'?nodes[c.path[i]].point:c.path[i];if(c.feet.distanceTo(p)>1.2)break;const y=walking.canStandTownAs('human',p.x,p.z,p.y,c.actor);if(y!==null){c.feet.set(p.x,y,p.z);c.cursor=i;exit=true;break;}}if(!exit)continue;}c.currentState='walking';}
  if(c.currentState==='walking'&&(c.routePause??0)>0){c.routePause-=step;continue;}
  const before=c.feet.clone();
  if(rate>0&&c.currentState==='walking')advanceHidden(c,step);
  else if(c.cursor<c.path.length){const segment=c.path[c.cursor],target=typeof segment==='number'?nodes[segment].point:segment,delta=target.clone().sub(c.feet),d=Math.hypot(delta.x,delta.z);if(!shopSystem.current&&walking.active&&walking.state.feet.distanceTo(c.feet)<.85){c.playerWait=(c.playerWait??0)+step;if(c.playerWait>2){c.playerWait=-3;const i=Math.min(c.cursor+22,c.path.length-1),goal=typeof c.path[i]==='number'?nodes[c.path[i]].point:c.path[i],detour=streetDetour({THREE,walking,actor:c.actor,start:c.feet,goal,player:walking.state.feet,limit:getQuality()==='mobile'?600:1800});if(detour)c.path.splice(c.cursor,i-c.cursor,...detour);}continue;}
   if(d<.015){c.feet.copy(target);if(typeof segment==='number')c.node=segment;c.cursor++;if(c.cursor%90===0&&c.cursor<c.path.length)c.routePause=c.id==='boatworker'?.65:1.1;if(c.cursor===c.path.length){c.place=c.destination;c.currentState=['inn','tavern'].includes(c.place)?'inside':'resting';}}
   else{const amount=Math.min(d,c.speed*step),n=Math.max(1,Math.ceil(amount/.06));for(let i=0;i<n;i++){const x=c.feet.x+delta.x/d*amount/n,z=c.feet.z+delta.z/d*amount/n,y=walking.canStandTownAs('human',x,z,c.feet.y,c.actor);if(y===null){const ax=walking.canStandTownAs('human',x,c.feet.z,c.feet.y,c.actor),az=walking.canStandTownAs('human',c.feet.x,z,c.feet.y,c.actor);if(ax!==null)c.feet.set(x,ax,c.feet.z);else if(az!==null)c.feet.set(c.feet.x,az,z);else break;}else c.feet.set(x,y,z);}c.actor.userData.travelYaw=Math.atan2(delta.x,delta.z);}
  }
  if(c.currentState==='walking'&&c.feet.distanceTo(before)<.00001){c.stalled=(c.stalled??0)+step;if(c.stalled>2){c.stalled=-3;for(let i=Math.min(c.cursor+18,c.path.length-1);i>c.cursor;i--){const goal=typeof c.path[i]==='number'?nodes[c.path[i]].point:c.path[i];if(walking.canStandTownAs('human',goal.x,goal.z,goal.y,c.actor)===null)continue;const detour=streetDetour({THREE,walking,actor:c.actor,start:c.feet,goal,player:!shopSystem.current&&walking.active?walking.state.feet:null,limit:getQuality()==='mobile'?600:1800});if(detour)c.path.splice(c.cursor,i-c.cursor,...detour);break;}}}else c.stalled=0;
  c.actor.userData.namedTravel={currentState:c.currentState,destination:c.destination,place:c.place};
 }}
 function draw(id){const c=controllers.get(id);if(!c)return false;if(c.actor.parent!==c.parent)c.parent.attach(c.actor);c.actor.visible=!['inn','tavern'].includes(c.place)||c.currentState==='walking';c.actor.position.copy(c.parent.worldToLocal(c.feet.clone().add(new THREE.Vector3(0,c.offset,0))));c.actor.rotation.y=c.actor.userData.travelYaw??0;return true;}
 const adapter={update,draw,get stats(){return {scheduled:controllers.size,moving:[...controllers.values()].filter(c=>['walking','departing'].includes(c.currentState)).length,inside:[...controllers.values()].filter(c=>c.currentState==='inside').length,hiddenUpdateInterval:.5}},location:id=>{const c=controllers.get(id);return c?c.currentState==='walking'?'town':c.place:shopSystem.locationFor(id)},controllers};shopSystem.setTravel(adapter);return adapter;
}
