// Pure predicates shared by acts, region unlocks and map travel. No scene state.
export const conditionSets={
 'low-water':{conditionalState:{water:['veryLow','extremeLow']}},
 'extreme-water':{conditionalState:{water:['extremeLow']}},
 descent:{requiredDiscoveries:['crown:entrance'],conditionalState:{water:['extremeLow']}},
 'crown-observation':{requiredDiscoveries:['ring:visit'],anyDiscoveries:['ring:center','ring:cat-2','ring:nerissa-reply','ring:direction']},
 'mire-exit':{requiredRegions:['hollow-crown'],requiredThreads:{hollowCrown:['visited','observed']},anyDiscoveries:['crown:crack','crown:sky','crown:cat-1','crown:mineral']},
 'mire-passage':{requiredDiscoveries:['mire:exit'],conditionalState:{water:['extremeLow']}},
 'mire-land':{requiredDiscoveries:['mire:exit']},
 'royal-road':{requiredDiscoveries:['mire:sign']}
};
export function regionVisited(data,id){return id==='bellmire'||!!data.discoveries?.['region:'+id]||!!data.discoveries?.[{'hollow-crown':'crown:visit','the-ring':'ring:visit','nine-stones':'nine:visit','lake-lun':'lake:visit','violet-mire':'mire:visit','drowned-way':'drowned:walk'}[id]];}
export function evaluateConditions(raw,data){const rule=typeof raw==='string'?conditionSets[raw]:raw;if(!rule)return !raw;const seen=id=>!!data.discoveries?.[id];return (!rule.requiredDay||data.currentDay>=rule.requiredDay)&&(rule.requiredRegions??[]).every(id=>regionVisited(data,id))&&(rule.requiredDiscoveries??[]).every(seen)&&(!rule.anyDiscoveries||rule.anyDiscoveries.some(seen))&&Object.entries(rule.requiredThreads??{}).every(([id,stages])=>stages.includes(data.threads?.[id]?.stage??'unseen'))&&(!rule.conditionalState?.water||rule.conditionalState.water.includes(data.waterLevelState?.phase??'normal'));}
export const chapters=[
 {chapterId:'bellmire',acts:[{actId:'daily-life',storyThreads:[],dependencies:[],unlockConditions:{},regionUnlocks:['bellmire'],journalHooks:['met:'],completedFlags:['region:nine-stones']},{actId:'bell',storyThreads:['bell'],dependencies:['daily-life'],unlockConditions:{anyDiscoveries:['bell-thread-heard','belfry-mark']},regionUnlocks:[],journalHooks:['bell-'],completedFlags:['bell-thread-night']}]},
 {chapterId:'lake-lands',acts:[{actId:'stones',storyThreads:[],dependencies:[],unlockConditions:{requiredRegions:['nine-stones']},regionUnlocks:['nine-stones'],journalHooks:['nine:'],completedFlags:['nine:stone-5']},{actId:'shore-life',storyThreads:[],dependencies:[],unlockConditions:{requiredRegions:['lake-lun']},regionUnlocks:['lake-lun','lunmere','caerith'],journalHooks:['lake:','lun:'],completedFlags:['region:lunmere']},{actId:'drowned',storyThreads:['drowned'],dependencies:['shore-life'],unlockConditions:{anyDiscoveries:['drowned:rumor','drowned:entry']},regionUnlocks:['drowned-way'],journalHooks:['drowned:'],completedFlags:['drowned:mark']},{actId:'ring',storyThreads:['ring'],dependencies:['drowned'],unlockConditions:{requiredRegions:['the-ring']},regionUnlocks:['the-ring'],journalHooks:['ring:'],completedFlags:['ring:direction']}]},
 {chapterId:'beyond-the-ring',acts:[{actId:'hollow',storyThreads:['hollowCrown'],dependencies:[],unlockConditions:{requiredDiscoveries:['crown:entrance']},regionUnlocks:['hollow-crown'],journalHooks:['crown:'],completedFlags:['crown:sky']},{actId:'mire',storyThreads:['violetMire'],dependencies:['hollow'],unlockConditions:'mire-land',regionUnlocks:['violet-mire'],journalHooks:['mire:'],completedFlags:['mire:reflection','mire:sign']}]}
];
// Reconstruct from authoritative discoveries/threads, never trust a saved unlock.
const threadEndStages={bell:['afterglow'],drowned:['linked'],ring:['compared'],hollowCrown:['observed'],violetMire:['reflected']};
export function deriveProgression(data){const acts={},chapterState={};for(const c of chapters){let entered=false;for(const a of c.acts){const active=evaluateConditions(a.unlockConditions,data)||a.storyThreads.some(id=>data.threads?.[id]?.stage&&data.threads[id].stage!=='unseen'),complete=(a.completedFlags.length>0&&a.completedFlags.every(id=>!!data.discoveries?.[id]))||a.storyThreads.some(id=>threadEndStages[id]?.includes(data.threads?.[id]?.stage));acts[c.chapterId+':'+a.actId]={chapterId:c.chapterId,actId:a.actId,stage:complete?'remembered':active?'present':'unseen',completedFlags:a.completedFlags.filter(id=>!!data.discoveries?.[id])};entered||=active;}chapterState[c.chapterId]=entered?'present':'unseen';}return{modelVersion:1,chapters:chapterState,acts};}
