// Short optional views preserve the player's safe feet and return immediately.
export function createQuietStay({THREE,camera,walking,shopSystem,inspections,stay}){
 let current=null;const button=document.createElement('button');button.className='quiet-return';button.textContent='歩行へ戻る';button.hidden=true;document.body.append(button);
 function end(){if(!current)return;camera.position.copy(current.position);camera.quaternion.copy(current.quaternion);current=null;button.hidden=true;walking.setInputBlocked('quiet-view',false);walking.update(0);}
 function begin(entry){if(!walking.active||current)return;inspections.dismiss();document.exitPointerLock?.();current={position:camera.position.clone(),quaternion:camera.quaternion.clone(),remaining:7,eye:camera.position.clone(),focus:null};if(!shopSystem.current){current.eye.copy(walking.state.feet).add(new THREE.Vector3(0,entry.id.includes('lookout')?2.1:1.05,0));current.focus=entry.id.includes('lookout')?new THREE.Vector3(-10,7,4):new THREE.Vector3(4,1.8,39);}else{current.eye.y=walking.state.feet.y+1.02;current.focus=current.eye.clone().add(new THREE.Vector3(-Math.sin(walking.state.yaw),0,-Math.cos(walking.state.yaw)));}walking.setInputBlocked('quiet-view',true);button.hidden=false;button.focus();stay.note('quiet:'+entry.id,entry.id.includes('lookout')?'丘で腰を下ろすと、街の鐘が少し遠くなった。':'少し腰を下ろした。声と水音は、そのまま続いている。',{kind:'stay'});}
 button.onclick=end;document.addEventListener('keydown',e=>{if(current&&['Escape','KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','Space'].includes(e.code))end();});walking.onLeave(end);
 for(const id of ['outskirts-rest','outskirts-lookout']){const e=inspections.resolver.entries.get(id);if(e){e.kind='quiet-view';e.verb=id==='outskirts-rest'?'座る':'眺める';}}
 shopSystem.onRoom(room=>{if(!room.seats?.length)return;const p=room.seats[0].position;inspections.resolver.register({id:'sit:'+room.shop.id,kind:'quiet-view',verb:'座る',label:'窓辺の席',object:room.root,localPoint:[p[0],p[1]+.8,p[2]],range:1.7,profiles:['human'],enabled:()=>shopSystem.current===room});});
 inspections.handlers.set('quiet-view',begin);return{begin,end,get active(){return !!current},update(dt){if(!current)return;if(!walking.active){end();return;}current.remaining-=dt;if(current.remaining<=0){end();return;}camera.position.copy(current.eye);camera.lookAt(current.focus);}};
}
