import {lakeLayout} from './lake-lun.js';
// Adding another region only requires data, terrain and its observation targets.
const target=(id,name,short,position)=>({id,name,short,position:[...position]});
const preset=(id,name,eye,focus)=>({id,name,eye,focus});
export function createRegionData(bellmirePresets,bellmireDestinations){return [
 {id:'bellmire',name:'Bellmire',description:'Bellmire — 路地の暮らしと深緑の屋根、猫が歩く丘の街',walkingBounds:{minX:-165,maxX:Infinity},entryPoint:[...(bellmireDestinations.find(d=>d.id==='inn')?.position??[0,1.38,32])],cameraPresets:bellmirePresets,navigationTargets:bellmireDestinations.filter(d=>d.id!=='nine-stones').concat(target('nine-stones','Nine Stones方面','九',[-173,9.85,-28])),mapBounds:{minX:-169,maxX:48,minZ:-48,maxZ:45},ambientProfile:'town'},
 {id:'nine-stones',name:'Nine Stones',description:'Nine Stones — 草と風の中に残る、九つの古い石',walkingBounds:{minX:-294,maxX:-165},entryPoint:[-173,9.8,-28],cameraPresets:[
 preset('nine-overview','全景',[-181,26,-11],[-192,10,-31]),preset('nine-stones','九石',[-185,13,-19],[-193,11,-32]),preset('nine-hill','丘',[-187,13,-43],[-191,10.6,-30]),preset('nine-road','街道',[-156,14,-12],[-181,10,-28]),preset('nine-bellmire','Bellmireを望む',[-173,13,-27],[-10,8,4]),preset('nine-lake','Lake Lun方面',[-200,14,-20],[-254,7,-30]),preset('nine-rest','風除け',[-173,12,-28],[-178,10,-32]),preset('nine-sign','道標',[-198,12,-18],[-203,10,-23])],navigationTargets:[target('nine-stones','九石','九',[-190,10,-30]),target('nine-hill','石群を見渡す丘','丘',[-187,11.26,-43]),target('bellmire','Bellmire方面','町',[-109,8.65,-14]),target('lake-lun','Lake Lun方面','湖',lakeLayout.entry)],mapBounds:{minX:-298,maxX:-159,minZ:-49,maxZ:-9},ambientProfile:'wind'},
 {id:'lake-lun',name:'Lake Lun',description:'Lake Lun — 静かな水、遠い岸、少し冷たい風',walkingBounds:{minX:-Infinity,maxX:-294},entryPoint:lakeLayout.entry,cameraPresets:[
 preset('lake-overview','全景',[-301,29,0],[-340,5.7,-24]),preset('lake-shore','湖岸',[-303,9,-32],[-322,6,-27]),preset('lake-pier','桟橋',[-312,10,-18],[-321,6,-24]),preset('lake-path','湖畔道',[-299,11,-46],[-310,6,-23]),preset('lake-boat','小舟',[-316,8,-29],[-321,6,-27]),preset('lake-water','水際',[-311,7.8,-34],[-325,5.7,-35]),preset('lake-far-shore','対岸',[-321,8,-24],[-374,7,-25]),preset('lake-nine','Nine Stones方面',[-305,12,-25],[-190,11,-30])],navigationTargets:[target('lake-entry','湖岸入口','岸',lakeLayout.entry),target('lake-pier','古い桟橋','桟',lakeLayout.pier),target('lake-path','湖畔道','道',[-308,6.04,-17]),target('nine-stones','Nine Stones方面','九',[-206.1,9.48,-23])],mapBounds:lakeLayout.bounds,ambientProfile:'quiet-water'}];}
export function createRegions({THREE,regions,walking,stay,shopSystem,inspections,quietStay,navigation,minimap,setCamera,getWalkingProfile,roads,onRegionChange=()=>{}}){
 let current=regions[0],elapsed=0;
 const selector=document.createElement('label');selector.className='region-picker';selector.textContent='地域：';const select=document.createElement('select');select.id='regionSelect';select.setAttribute('aria-label','訪問済み地域へ再訪');selector.append(select);const panel=document.getElementById('panel');panel.insertBefore(selector,panel.firstChild);
 const status=document.createElement('span');status.className='region-location';status.setAttribute('aria-live','polite');selector.append(status);
 const buttons=document.getElementById('views'),oldButtons=[...buttons.children];
 const visited=r=>r.id==='bellmire'||!!stay.data.discoveries['region:'+r.id]||r.id==='nine-stones'&&!!stay.data.discoveries['nine:visit']||r.id==='lake-lun'&&!!stay.data.discoveries['lake:visit'];
 const classify=p=>regions.find(r=>p.x>=r.walkingBounds.minX&&p.x<r.walkingBounds.maxX)??current;
 function refresh(){select.replaceChildren();for(const r of regions){const o=new Option(r.name+(visited(r)?'':'（未訪問）'),r.id);o.disabled=!visited(r);select.add(o);}select.value=current.id;status.textContent='現在地：'+current.name;}
 function apply(r){current=r;onRegionChange(r);refresh();const title=document.querySelector('#panel .title');if(title?.firstChild?.nodeType===3)title.firstChild.textContent=r.name.toUpperCase()+' ';const sub=document.querySelector('#panel .sub');if(sub)sub.textContent=r.description??r.name;buttons.replaceChildren();if(r.id==='bellmire')buttons.append(...oldButtons);else for(const c of r.cameraPresets){const b=document.createElement('button');b.dataset.v=c.id;b.textContent=c.name;buttons.append(b);}navigation.setDestinations(r.navigationTargets);minimap.setRegion({...r,roads:roads[r.id]??[]});}
 function mark(r){if(visited(r))return;stay.data.discoveries['region:'+r.id]={day:stay.data.currentDay,period:stay.data.dayPhase,playerMode:walking.state.profile.id,label:r.name};stay.changed();}
 function revisit(id){const r=regions.find(r=>r.id===id);if(!r||!visited(r)){refresh();return false;}quietStay.end();inspections.dismiss();if(shopSystem.current)shopSystem.exit();const profile=walking.active?walking.state.profile.id:getWalkingProfile();if(!walking.active)walking.enter(profile);
 // Validate before relocating; neither DOM manipulation nor saved flags can
 // put the player inside a wall or over unsupported water.
 const [x,y,z]=r.entryPoint,ground=walking.canStandTownAs(profile,x,z,y);if(ground===null){refresh();return false;}walking.relocate(new THREE.Vector3(x,ground,z),{yaw:r.id==='bellmire'?Math.PI:Math.PI/2});navigation.choose('');apply(r);return true;}
 select.onchange=()=>revisit(select.value);
 function camera(id){const c=regions.flatMap(r=>r.cameraPresets).find(c=>c.id===id);if(!c)return false;setCamera(c);return true;}
 function update(dt){elapsed+=dt;if(elapsed<.5)return;elapsed=0;if(!walking.active||shopSystem.current)return;const r=classify(walking.state.feet);if(r!==current){mark(r);apply(r);}else if(!visited(r)){mark(r);refresh();}}
 apply(current);stay.onChange?.(()=>refresh());return{regions,select,revisit,camera,update,get current(){return current},get data(){return regions.map(r=>({...r,visited:visited(r)}));},refresh};
}
