import {recordTravel} from './world-graph.js';
import {lunmereLayout,lunmereShops} from './lunmere-data.js';
import {caerithLayout} from './caerith.js';
import {lakeLayout} from './lake-lun.js';
// Adding another region only requires data, terrain and its observation targets.
const target=(id,name,short,position)=>({id,name,short,position:[...position]});
const preset=(id,name,eye,focus)=>({id,name,eye,focus});
export function createRegionData(bellmirePresets,bellmireDestinations){return [
 {id:'bellmire',name:'Bellmire',description:'Bellmire — 路地の暮らしと深緑の屋根、猫が歩く丘の街',walkingBounds:{minX:-165,maxX:Infinity},entryPoint:[...(bellmireDestinations.find(d=>d.id==='inn')?.position??[0,1.38,32])],cameraPresets:bellmirePresets,navigationTargets:bellmireDestinations.filter(d=>d.id!=='nine-stones').concat(target('nine-stones','Nine Stones方面','九',[-173,9.85,-28])),mapBounds:{minX:-169,maxX:48,minZ:-48,maxZ:45},ambientProfile:'town'},
 {id:'nine-stones',name:'Nine Stones',description:'Nine Stones — 草と風の中に残る、九つの古い石',walkingBounds:{minX:-294,maxX:-165},entryPoint:[-173,9.8,-28],cameraPresets:[
 preset('nine-overview','全景',[-181,26,-11],[-192,10,-31]),preset('nine-stones','九石',[-185,13,-19],[-193,11,-32]),preset('nine-hill','丘',[-187,13,-43],[-191,10.6,-30]),preset('nine-road','街道',[-156,14,-12],[-181,10,-28]),preset('nine-bellmire','Bellmireを望む',[-173,13,-27],[-10,8,4]),preset('nine-lake','Lake Lun方面',[-200,14,-20],[-254,7,-30]),preset('nine-rest','風除け',[-173,12,-28],[-178,10,-32]),preset('nine-sign','道標',[-198,12,-18],[-203,10,-23])],navigationTargets:[target('nine-stones','九石','九',[-190,10,-30]),target('nine-hill','石群を見渡す丘','丘',[-187,11.26,-43]),target('bellmire','Bellmire方面','町',[-109,8.65,-14]),target('lake-lun','Lake Lun方面','湖',lakeLayout.entry)],mapBounds:{minX:-298,maxX:-159,minZ:-49,maxZ:-9},ambientProfile:'wind'},
 {id:'lake-lun',name:'Lake Lun',description:'Lake Lun — 静かな水、遠い岸、少し冷たい風',walkingBounds:{minX:-397,maxX:-294},entryPoint:lakeLayout.entry,cameraPresets:[
 preset('lake-overview','全景',[-301,29,0],[-340,5.7,-24]),preset('lake-shore','湖岸',[-303,9,-32],[-322,6,-27]),preset('lake-pier','桟橋',[-312,10,-18],[-321,6,-24]),preset('lake-path','湖畔道',[-299,11,-46],[-310,6,-23]),preset('lake-boat','小舟',[-316,8,-29],[-321,6,-27]),preset('lake-water','水際',[-311,7.8,-34],[-325,5.7,-35]),preset('lake-far-shore','対岸',[-321,8,-24],[-374,7,-25]),preset('lake-nine','Nine Stones方面',[-305,12,-25],[-190,11,-30])],navigationTargets:[target('lake-entry','湖岸入口','岸',lakeLayout.entry),target('lake-pier','古い桟橋','桟',lakeLayout.pier),target('lake-path','湖畔道','道',[-309,6.04,-17]),target('nine-stones','Nine Stones方面','九',[-206.1,9.48,-23]),target('lunmere','Lunmere方面','町',lunmereLayout.entry)],mapBounds:{...lakeLayout.bounds,minX:-397,maxZ:24},ambientProfile:'quiet-water'},
 {id:'lunmere',name:'Lunmere',description:'Lunmere — 木立と湖、静かな屋根の小さな町',walkingBounds:{minX:-Infinity,maxX:-397},entryPoint:lunmereLayout.entry,cameraPresets:[
 preset('lun-overview','全景',[-382,45,70],[-429,6,12]),preset('lun-shore','湖畔',[-427,9,9],[-428,6,-10]),preset('lun-inn','宿屋',[-414,12,45],[-422,8,34]),preset('lun-diner','食堂',[-431,11,16],[-438,8,5]),preset('lun-boats','舟小屋',[-402,10,15],[-413,8,4]),preset('lun-store','商店',[-437,11,42],[-443,8,32]),preset('lun-square','小広場',[-420,13,28],[-430,6,22]),preset('lun-pier','桟橋',[-412,9,5],[-418,6,-4]),preset('lun-path','湖畔道',[-384,13,25],[-352,6,14]),preset('lun-lake','Lake Lun方面',[-399,12,13],[-339,6,-23])],navigationTargets:[target('lun-entry','Lunmere入口','門',lunmereLayout.entry),target('lun-square','湖畔の小広場','広',lunmereLayout.square),target('lun-pier','桟橋','桟',lunmereLayout.pier),...lunmereShops.map(s=>target(s.id,s.name,s.name.slice(0,1),[s.center[0],6.16,s.center[1]+s.size[1]/2+1.4])),target('lake-lun','Lake Lun方面','湖',[-308,6.04,-17])],mapBounds:lunmereLayout.bounds,ambientProfile:'lakeside-town'},
 {id:'caerith',name:'Isle of Caerith',description:'Isle of Caerith — 湖風と草、古い灰石の島',walkingBounds:{minX:-387,maxX:-347,minZ:-98,maxZ:-50},entryPoint:caerithLayout.entry,requiresBoat:true,cameraPresets:[
 preset('caerith-overview','全景',[-338,29,-48],[-367,7,-76]),preset('caerith-landing','船着場',[-360,10,-49],[-367,6,-55]),preset('caerith-tower','塔跡',[-360,12,-75],[-370,9,-81]),preset('caerith-foundation','円形基礎',[-362,14,-70],[-367,7,-78]),preset('caerith-hill','高台',[-361,10,-86],[-367,7,-76]),preset('caerith-lunmere','Lunmere方向',[-373,10,-84],[-429,8,14]),preset('caerith-lake','Lake Lun方向',[-362,10,-84],[-333,6,-24])],navigationTargets:[target('caerith-landing','船着場','桟',caerithLayout.entry),target('caerith-tower','塔跡','塔',[-367,7.2,-72]),target('caerith-hill','高台','丘',[-362,6.8,-84]),target('lunmere','Lunmere方向','町',lunmereLayout.pier)],mapBounds:caerithLayout.bounds,ambientProfile:'cold-lake-wind'}];}
export function createRegions({THREE,regions,walking,stay,shopSystem,inspections,quietStay,navigation,minimap,setCamera,getWalkingProfile,roads,onRegionChange=()=>{}}){
 let current=regions[0],elapsed=0;
 const selector=document.createElement('label');selector.className='region-picker';selector.textContent='地域：';const select=document.createElement('select');select.id='regionSelect';select.setAttribute('aria-label','訪問済み地域へ再訪');selector.append(select);const panel=document.getElementById('panel');panel.insertBefore(selector,panel.firstChild);
 const wardLabel=document.createElement('label');wardLabel.className='region-picker';wardLabel.textContent='区画：';const wardSelect=document.createElement('select');wardSelect.id='capitalWardSelect';wardLabel.append(wardSelect);selector.after(wardLabel);wardLabel.hidden=true;
 const status=document.createElement('span');status.className='region-location';status.setAttribute('aria-live','polite');selector.append(status);
 const buttons=document.getElementById('views'),oldButtons=[...buttons.children];
 const visited=r=>r.id==='bellmire'||(r.visitedFlags??[]).some(id=>!!stay.data.discoveries[id])||!!stay.data.discoveries['region:'+r.id]||r.id==='nine-stones'&&!!stay.data.discoveries['nine:visit']||r.id==='lake-lun'&&!!stay.data.discoveries['lake:visit'];
 const classify=p=>[...regions.filter(r=>r.conditional&&r.enabled()),...regions.filter(r=>r.requiresBoat),...regions.filter(r=>!r.requiresBoat&&!r.conditional)].find(r=>p.x>=r.walkingBounds.minX&&p.x<r.walkingBounds.maxX&&(!r.contains||r.contains(p))&&(r.walkingBounds.minZ===undefined||p.z>=r.walkingBounds.minZ&&p.z<=r.walkingBounds.maxZ))??current;
 function refresh(){select.replaceChildren();for(const r of regions){if(r.parentRegion||r.visible&&!r.visible())continue;const o=new Option(r.name+(visited(r)?'':'（未訪問）'),r.id);o.disabled=!visited(r)||(r.enabled&&!r.enabled());if(r.enabled&&!r.enabled())o.textContent=r.name+'（'+(r.disabledLabel??'水没')+'）';select.add(o);}select.value=current.parentRegion??current.id;wardLabel.hidden=!(current.parentRegion==='caer-veyra'||current.id==='caer-veyra');wardSelect.replaceChildren();if(!wardLabel.hidden)for(const r of regions.filter(r=>r.parentRegion==='caer-veyra')){if(r.visible&&!r.visible())continue;const o=new Option(r.name.replace('Caer Veyra · ','' )+(visited(r)?'':'（未訪問）'),r.id);o.disabled=!visited(r)||(r.enabled&&!r.enabled());wardSelect.add(o);}wardSelect.value=current.id;status.textContent='現在地：'+current.name;for(const b of buttons.children){const c=current.cameraPresets.find(c=>c.id===b.dataset.v);if(c?.visible)b.hidden=!c.visible();if(c?.enabled){b.disabled=!c.enabled();b.textContent=b.disabled?(c.disabledLabel??c.name):c.name;}}}
 function apply(r,travelMode='road'){current=r;if(recordTravel(stay.data,r.id,walking.state.profile.id,document.body.classList.contains('boating')?'boat':travelMode))stay.changed();onRegionChange(r);const title=document.querySelector('#panel .title');if(title?.firstChild?.nodeType===3)title.firstChild.textContent=r.name.toUpperCase()+' ';const sub=document.querySelector('#panel .sub');if(sub)sub.textContent=r.description??r.name;buttons.replaceChildren();if(r.id==='bellmire')buttons.append(...oldButtons);else for(const c of r.cameraPresets){const b=document.createElement('button');b.dataset.v=c.id;b.textContent=c.name;buttons.append(b);}navigation.setDestinations(r.navigationTargets.filter(d=>!d.enabled||d.enabled()));minimap.setRegion({...r,roads:roads[r.id]??[]});refresh();}
 function mark(r){if(r.markOnEnter===false||visited(r)||r.requiresBoat)return;stay.data.discoveries['region:'+r.id]={day:stay.data.currentDay,period:stay.data.dayPhase,playerMode:walking.state.profile.id,label:r.name};stay.changed();}
 function revisit(id){const r=regions.find(r=>r.id===id);if(!r||!visited(r)||(r.enabled&&!r.enabled())){refresh();return false;}api.beforeRevisit?.(id);quietStay.end();inspections.dismiss();if(shopSystem.current)shopSystem.exit();const profile=walking.active?walking.state.profile.id:getWalkingProfile();if(!walking.active)walking.enter(profile);
 // Validate before relocating; neither DOM manipulation nor saved flags can
 // put the player inside a wall or over unsupported water.
 walking.refreshDynamic(true);const [x,y,z]=r.entryPoint,ground=walking.canStandTownAs(profile,x,z,y);if(ground===null){refresh();return false;}walking.relocate(new THREE.Vector3(x,ground,z),{yaw:r.id==='bellmire'?Math.PI:Math.PI/2});navigation.choose('');apply(r,'revisit');return true;}
 select.onchange=()=>revisit(select.value);wardSelect.onchange=()=>revisit(wardSelect.value);
 function camera(id){const c=regions.flatMap(r=>r.cameraPresets).find(c=>c.id===id);if(!c||(c.enabled&&!c.enabled()))return false;setCamera(c);return true;}
 function update(dt){elapsed+=dt;if(elapsed<.5)return;elapsed=0;if(!walking.active||shopSystem.current)return;const r=classify(walking.state.feet);if(r!==current){mark(r);apply(r);}else if(!visited(r)){mark(r);refresh();}}
 apply(current);stay.onChange?.(()=>refresh());const api={showRegion:id=>{const r=regions.find(r=>r.id===id);if(r)apply(r);},refreshArea:()=>apply(current),regions,select,wardSelect,revisit,camera,update,get current(){return current},get data(){return regions.map(r=>({...r,visited:visited(r)}));},refresh};return api;
}
