import {visitorPresent} from './town-calendar.js';
import {residentStreetPaths} from './resident-routes.js';
// Extend the original eight scheduled residents. Only the clock requests paths;
// the same human feet/body policy validates every actual movement substep.
export function createResidentDay({THREE,walking,grounding,residentLife,townLife,shopSystem,camera=null,getQuality=()=> 'standard'}){
 const records=residentLife.records.filter(r=>!r.id&&!r.moving&&!r.seated).slice(0,8);for(const r of records)walking.registerDynamicObject(r.object);
 const nodes=[],keys=new Map(),paths={};
 const key=p=>p.map(v=>v.toFixed(3)).join(',');
 for(const [id,path]of Object.entries(residentStreetPaths)){paths[id]=path.map(p=>{const k=key(p);if(!keys.has(k)){keys.set(k,nodes.length);let y=p[1]||(walking.groundAt(p[0],p[2],Infinity,walking.profiles.human)??grounding.heightAt(p[0],p[2])),point=new THREE.Vector3(p[0],y,p[2]);const bridgeFloor=walking.groundAt(p[0],p[2],Infinity,walking.profiles.human);if(bridgeFloor!==null&&bridgeFloor>y&&bridgeFloor-y<.7){y=bridgeFloor;point.y=y;}const candidates=[[0,0]];for(const r of [.001,.003,.008])for(let i=0;i<8;i++)candidates.push([Math.sin(i*Math.PI/4)*r,Math.cos(i*Math.PI/4)*r]);for(const [dx,dz]of candidates){const floor=walking.canStandTownAs('human',p[0]+dx,p[2]+dz,y);if(floor!==null){point.set(p[0]+dx,floor,p[2]+dz);break;}}nodes.push({point,links:new Set()});}return keys.get(k);});for(let i=1;i<paths[id].length;i++){nodes[paths[id][i-1]].links.add(paths[id][i]);nodes[paths[id][i]].links.add(paths[id][i-1]);}}
 function route(start,end){if(start===end)return [];const open=[start],cost=new Map([[start,0]]),previous=new Map();while(open.length){open.sort((a,b)=>(cost.get(a)+nodes[a].point.distanceTo(nodes[end].point))-(cost.get(b)+nodes[b].point.distanceTo(nodes[end].point)));const n=open.shift();if(n===end){const out=[];for(let i=end;i!==start;i=previous.get(i))out.push(i);return out.reverse();}for(const next of nodes[n].links){const c=cost.get(n)+nodes[n].point.distanceTo(nodes[next].point);if(c<(cost.get(next)??Infinity)){cost.set(next,c);previous.set(next,n);if(!open.includes(next))open.push(next);}}}return [];}
 paths.harbor=paths.bookshop.slice(0,60); // Work on the quay, away from the player spawn.
 const dayPlaces=['market','square','harbor','bakery','bookshop','mill','market','square'];
 const entries=records.map((record,i)=>{const o=record.object;o.updateWorldMatrix(true,true);const home=paths[dayPlaces[i]][Math.max(0,paths[dayPlaces[i]].length-1-(25+i*5))],point=nodes[home].point;
  const offset=o.getWorldPosition(new THREE.Vector3()).y-new THREE.Box3().setFromObject(o,true).min.y;
  return {record,index:i,parent:o.parent,home,node:home,feet:point.clone(),offset,route:[],cursor:0,speed:.78+i*.045,wait:0,pause:0,elapsed:0,currentState:'idle',destination:dayPlaces[i],schedule:{morning:dayPlaces[i],day:dayPlaces[i],evening:i<4?'tavern':dayPlaces[i],night:i<3?'tavern':i===3?'inn':'home'},inside:null,visible:true,returnTrail:[]};});
 let period=townLife.state.period,weather=townLife.state.weather,day=townLife.state.dayIndex,calendar=townLife.state.calendar,lastRoom=null,roomDirty=false;const changes=[];const counters={pathRequests:0,updated:0,near:0,mid:0,far:0};
 function remember(e){const last=e.returnTrail.at(-1);if(!last||last.distanceTo(e.feet)>.025)e.returnTrail.push(e.feet.clone());}
 function place(e){if(shopSystem.current)return;const o=e.record.object;if(o.parent!==e.parent)e.parent.attach(o);o.position.copy(o.parent.worldToLocal(e.feet.clone().add(new THREE.Vector3(0,e.offset,0))));o.visible=e.visible;e.record.currentState=e.currentState;o.userData.dailyLife={currentState:e.currentState,destination:e.destination,schedule:e.schedule};}
 function request(e){
  if(e.visitor){const present=visitorPresent(e.visitor,day);if(!present&&!e.spawned||e.departed&&!present){e.visible=false;e.currentState='away';return;}if(present&&!e.spawned){e.spawned=true;e.departed=false;e.visible=true;}e.leaving=!present;e.destination=present?(weather==='rain'||weather==='blackout'?'inn':e.schedule[period]):'origin';}else e.destination=weather==='blackout'&&[1,2,6].includes(e.index)?'tavern':weather==='rain'&&[0,6].includes(e.index)?'inn':weather==='dawn'&&period==='morning'&&[3,4,6,7].includes(e.index)?'inn':e.schedule[period];
  if(!e.visitor&&calendar?.gathering&&[0,1].includes(e.index))e.destination='mill';
  else if(!e.visitor&&calendar?.market&&[1,7].includes(e.index))e.destination='market';
  else if(!e.visitor&&calendar?.cycleDay===2&&e.index===2&&period==='day'&&weather==='clear')e.destination='market';
  if(e.inside===e.destination){e.currentState='inside';return;}const goal=e.visitor&&e.destination==='origin'?e.home:e.destination==='home'||e.destination===dayPlaces[e.index]?e.home:paths[e.destination].at(-1);e.marginPoint=null;e.parkingElapsed=0;e.route=[...e.returnTrail.slice().reverse(),e.node,...route(e.node,goal)];e.returnTrail=[];e.cursor=0;e.wait=.6+e.index*.7;e.record.prop.visible=true;e.departingShop=e.inside;e.inside=null;e.visible=!e.departingShop;e.currentState=e.route.length?(period==='night'&&e.destination==='home'?'goingHome':'walking'):'working';e.record.activity=period==='morning'?(e.index%2?'carrying':'sweeping'):e.record.role.activity;counters.pathRequests++;}
 function arrive(e){if(e.visitor&&e.leaving){e.departed=true;e.spawned=false;e.visible=false;e.inside=null;e.currentState='away';return;}const oldInside=e.inside;e.currentState=e.destination==='home'&&period==='night'?'resting':['tavern','inn'].includes(e.destination)?'inside':'working';e.record.activity=e.currentState==='inside'?'conversation':e.currentState==='resting'?'resting':e.record.role.activity;if(e.currentState==='inside'){e.record.prop.visible=false;e.inside=e.destination;e.visible=false;}else if(e.destination==='home'&&period==='night')e.visible=false;if(oldInside!==e.inside)roomDirty=true;}
 function refreshRoom(){const room=shopSystem.current;lastRoom=room?.shop.id??null;for(const e of entries){const o=e.record.object;if(o.parent!==e.parent)e.parent.attach(o);if(room){o.visible=e.inside===room.shop.id;if(o.visible){let found=false;for(const z of [2.2,.7,-.8,-2.2])for(const x of [-2.8,-1.8,-.8,.4,1.5,2.7]){if(found)break;const p=new THREE.Vector3(200+x,0,z),y=walking.canStandActor('human',p.x,p.z,0,o);if(y!==null){p.y=y;room.root.attach(o);o.position.copy(room.root.worldToLocal(p.add(new THREE.Vector3(0,e.offset,0))));walking.refreshDynamic();found=true;}}if(!found)o.visible=false;}}else place(e);}if(room){const guests=entries.filter(e=>e.record.object.parent===room.root&&e.record.object.visible);for(let i=0;i+1<guests.length;i+=2){const a=guests[i].record.object,b=guests[i+1].record.object;a.rotation.y=Math.atan2(b.position.x-a.position.x,b.position.z-a.position.z);b.rotation.y=a.rotation.y+Math.PI;guests[i].record.activity=guests[i+1].record.activity='conversation';}}}
 townLife.onChange(state=>{if(state.period===period&&state.weather===weather&&state.dayIndex===day)return;period=state.period;weather=state.weather;day=state.dayIndex;calendar=state.calendar;entries.forEach(request);if(shopSystem.current)refreshRoom();});
 for(const e of entries){request(e);place(e);} // Initial scene placement only, never a time-change teleport.
 function update(dt=.016){if((shopSystem.current?.shop.id??null)!==lastRoom)refreshRoom();walking.refreshDynamic();
  counters.updated=counters.near=counters.mid=counters.far=0;
  for(const e of entries){const distance=camera?camera.position.distanceTo(e.feet):0,tier=distance<18?'near':distance<42?'mid':'far';counters[tier]++;e.elapsed+=Math.min(.1,Math.max(0,dt));const rate=shopSystem.current?.5:tier==='near'?0:tier==='mid'?.10:getQuality()==='mobile'?.5:.25;if(e.elapsed<rate)continue;const stepTime=Math.min(.5,e.elapsed);e.elapsed=0;counters.updated++;
   if(e.departingShop){e.wait-=stepTime;if(e.wait<=0&&walking.canStandTownAs('human',e.feet.x,e.feet.z,e.feet.y,e.record.object)!==null){e.departingShop=null;e.visible=true;place(e);walking.refreshDynamic();}else place(e);continue;}
   if(e.inside||!e.visible){place(e);continue;}
   if(!shopSystem.current&&walking.active&&Math.abs(walking.state.feet.y-e.feet.y)<.5&&walking.state.feet.distanceTo(e.feet)<1.25){const w=walking.state,oldDistance=w.feet.distanceTo(e.feet);let yielded=false;for(let attempt=0;attempt<10;attempt++){const amount=Math.min(.12,.8*stepTime),angle=attempt<2?w.yaw+Math.PI/2+attempt*Math.PI:Math.atan2(e.feet.x-w.feet.x,e.feet.z-w.feet.z)+(attempt-2)*Math.PI/4,x=e.feet.x+Math.sin(angle)*amount,z=e.feet.z+Math.cos(angle)*amount,y=walking.canStandTownAs('human',x,z,e.feet.y,e.record.object);if(y!==null&&Math.abs(y-e.feet.y)<=walking.profiles.human.stepDown+.001&&Math.hypot(x-w.feet.x,z-w.feet.z)>=oldDistance-1e-6){remember(e);e.feet.set(x,y,z);remember(e);yielded=true;break;}}e.record.activity='listening';e.pause+=stepTime;if(yielded||oldDistance<.75){place(e);continue;}}
   // Yielding may use a validated bridge approach step, not just perfectly flat ground.
   const passing=entries.find(other=>other!==e&&other.visible&&!other.inside&&other.cursor<other.route.length&&other.feet.distanceTo(e.feet)<1.3);
   if(passing&&(e.cursor>=e.route.length||passing.index<e.index&&passing.feet.distanceTo(e.feet)<1.05)){let moved=false;const old=e.feet.distanceTo(passing.feet),away=Math.atan2(e.feet.x-passing.feet.x,e.feet.z-passing.feet.z);for(let i=0;i<8;i++){const angle=away+i*Math.PI/4,amount=Math.min(.1,.7*stepTime),x=e.feet.x+Math.sin(angle)*amount,z=e.feet.z+Math.cos(angle)*amount,y=walking.canStandTownAs('human',x,z,e.feet.y,e.record.object);if(y!==null&&Math.abs(y-e.feet.y)<=walking.profiles.human.stepDown+.001&&Math.hypot(x-passing.feet.x,z-passing.feet.z)>old+.001){remember(e);e.feet.set(x,y,z);remember(e);moved=true;break;}}if(moved){e.marginPoint=e.feet.clone();place(e);continue;}}
   if(e.wait>0){e.wait-=stepTime;place(e);continue;}
   if(e.cursor>=e.route.length&&!e.marginPoint&&!['tavern','inn','home'].includes(e.destination)){
    const center=nodes[e.node].point,previous=nodes[[...nodes[e.node].links][0]]?.point??center.clone().add(new THREE.Vector3(0,0,1)),tangent=center.clone().sub(previous).setY(0).normalize();
    outer:for(const distance of [.65,.85,1.05])for(const sign of [-1,1]){const p=center.clone().add(new THREE.Vector3(tangent.z,0,-tangent.x).multiplyScalar(distance*sign));let y=e.feet.y,clear=true;for(let i=1;i<=16;i++){const q=center.clone().lerp(p,i/16),floor=walking.canStandTownAs('human',q.x,q.z,y,e.record.object);if(floor===null||Math.abs(floor-center.y)>.04){clear=false;break;}y=floor;}if(clear&&Math.abs(y-center.y)<.04){p.y=y;e.marginPoint=p;break outer;}}
   }
   if(e.cursor>=e.route.length&&e.marginPoint){e.parkingElapsed=(e.parkingElapsed??0)+stepTime;if(e.parkingElapsed>8){e.marginPoint=e.feet.clone();arrive(e);place(e);continue;}}
   if(e.cursor>=e.route.length&&(!e.marginPoint||e.feet.distanceTo(e.marginPoint)<.006)){arrive(e);place(e);continue;}
   if(e.returnTrail.length&&e.cursor<e.route.length){e.route.splice(e.cursor,0,...e.returnTrail.slice().reverse());e.returnTrail=[];}
   const segment=e.route[e.cursor],target=e.cursor>=e.route.length?e.marginPoint:typeof segment==='number'?nodes[segment].point:segment,delta=target.clone().sub(e.feet),distance2=Math.hypot(delta.x,delta.z),move=Math.min(distance2,e.speed*stepTime);
   if(!shopSystem.current&&walking.active&&walking.state.feet.distanceTo(e.feet)<.72&&Math.abs(walking.state.feet.y-e.feet.y)<.5){e.pause+=stepTime;e.record.activity='listening';place(e);continue;}
   const neighbor=entries.find(other=>other!==e&&other.visible&&!other.inside&&other.feet.distanceTo(e.feet)<.52&&other.cursor<other.route.length&&other.index<e.index);
   if(neighbor){if(e.route.length&&e.feet.distanceTo(nodes[e.route.at(-1)].point)<1.15){e.cursor=e.route.length;arrive(e);if(!e.inside){e.currentState=neighbor.currentState='talking';e.record.activity=neighbor.record.activity='conversation';}}else e.wait=.25;place(e);continue;}
   if(distance2<.006&&e.cursor>=e.route.length){arrive(e);place(e);continue;}
   if(distance2<.006){const floor=walking.canStandTownAs('human',target.x,target.z,e.feet.y,e.record.object);if(floor===null){e.wait=.4;place(e);continue;}e.feet.set(target.x,floor,target.z);if(typeof segment==='number')e.node=segment;e.cursor++;if(e.cursor%70===0)e.wait=.5+e.index*.11;place(e);continue;}
   const offRoute=e.cursor>=e.route.length;if(offRoute)remember(e);
   const n=Math.max(1,Math.ceil(move/.06));let advanced=false;
   for(let j=0;j<n;j++){const x=e.feet.x+delta.x/distance2*move/n,z=e.feet.z+delta.z/distance2*move/n,y=walking.canStandTownAs('human',x,z,e.feet.y,e.record.object);if(y===null){const ax=walking.canStandTownAs('human',x,e.feet.z,e.feet.y,e.record.object),az=walking.canStandTownAs('human',e.feet.x,z,e.feet.y,e.record.object);if(ax!==null){e.feet.set(x,ax,e.feet.z);advanced=true;}else if(az!==null){e.feet.set(e.feet.x,az,z);advanced=true;}else {e.wait=.4;break;}}else{e.feet.set(x,y,z);advanced=true;}}
   if(offRoute)remember(e);
   if(advanced){e.record.object.rotation.y=Math.atan2(delta.x,delta.z);e.record.walkPhase=(e.record.walkPhase??0)+move*6;e.record.activity='walking';e.currentState=e.destination==='home'&&period==='night'?'goingHome':'walking';}
   place(e);
  }
  // A small exchange at shared destinations; no dialogue UI or extra people.
  for(let i=0;i<entries.length;i++)for(let j=i+1;j<entries.length;j++){const a=entries[i],b=entries[j];if(a.visible&&b.visible&&!a.inside&&!b.inside&&a.cursor>=a.route.length&&b.cursor>=b.route.length&&a.feet.distanceTo(b.feet)<1.8){a.currentState=b.currentState='talking';a.record.activity=b.record.activity='conversation';a.record.object.rotation.y=Math.atan2(b.feet.x-a.feet.x,b.feet.z-a.feet.z);b.record.object.rotation.y=a.record.object.rotation.y+Math.PI;}}
  if(roomDirty){roomDirty=false;if(shopSystem.current)refreshRoom();}
  changes.splice(0,changes.length,...entries.map(e=>({index:e.index,currentState:e.currentState,activity:e.record.activity,visible:e.record.object.visible,position:e.feet.toArray()})));
 }
 function addVisitor(record,definition){const origin=definition.origin==='cable'?'cable':'harbor',home=paths[origin][Math.max(0,paths[origin].length-1-(definition.id==='boat-carrier'?22:0))],o=record.object;walking.registerDynamicObject(o);o.updateWorldMatrix(true,true);const offset=o.getWorldPosition(new THREE.Vector3()).y-new THREE.Box3().setFromObject(o,true).min.y;const e={record,index:entries.length,parent:o.parent,home,node:home,feet:nodes[home].point.clone(),offset,route:[],cursor:0,speed:.86+(entries.length%3)*.07,wait:0,pause:0,elapsed:0,currentState:'away',destination:'origin',schedule:definition.schedule,inside:null,visible:false,returnTrail:[],visitor:definition,spawned:false,departed:false};entries.push(e);request(e);place(e);return e;}
 return {addVisitor,entries,changes,update,nodes,paths,route,get stats(){return {scheduled:entries.length,period,outsideVisible:entries.filter(e=>e.visible&&!e.inside).length,walking:entries.filter(e=>['walking','goingHome'].includes(e.currentState)).length,inside:entries.filter(e=>e.inside).length,addedResidents:entries.filter(e=>e.visitor).length,...counters};}};
}
