// Bellmire's first thread is observation-led and one-shot, never a quest list.
export const bellMarks=['outskirts-stone','moorings','event:upstream-stone','belfry-mark','star-chart'];
export function bellProgress(data,period){const t=data.threads?.bell??{stage:'unseen',anomalyDay:null,catFound:false};const seen=bellMarks.filter(id=>data.discoveries[id]);return {seen,eligible:data.currentDay>=3&&seen.length>=2&&period==='night'&&!t.anomalyDay,afterglow:!!t.anomalyDay&&data.currentDay>t.anomalyDay};}
export function createStoryThread({THREE,stay,townLife,inspections,dialogue,ambientAudio,residentLife,walking,shopSystem,catPassages}){
 stay.data.threads??={};stay.data.threads.bell??={stage:'unseen',anomalyDay:null,catFound:false};let busy=false,nightDelay=0,pending=false,reactUntil=0,elapsed=0;
 const t=()=>stay.data.threads.bell;
 function sync(){if(busy)return;busy=true;try{const d=stay.data,p=bellProgress(d,townLife.state.period);if(p.afterglow&&t().stage!=='afterglow'){t().stage='afterglow';stay.changed();}if(d.currentDay>=3&&p.seen.length>=2){stay.note('bell-thread-linked','同じものではない。でも、どこか似ている。',{kind:'place'});if(!t().anomalyDay&&t().stage!=='linked'){t().stage='linked';stay.changed();}}if(p.eligible&&!pending){pending=true;nightDelay=10;}}finally{busy=false;}}
 stay.onChange(sync);townLife.onChange(()=>{if(townLife.state.period!=='night'){pending=false;reactUntil=0;for(const r of reactions)r.bellPause=0;}sync();});
 const reactions=residentLife.records.filter(r=>!r.id&&!r.seated).slice(0,3);
 function begin(){if(!bellProgress(stay.data,townLife.state.period).eligible)return;t().stage='anomaly';t().anomalyDay=stay.data.currentDay;reactUntil=12;for(const r of reactions)r.bellPause=8;stay.note('bell-thread-night','いつもの鐘が止んだあと、もう一つの響きが水の向こうへ残った。',{kind:'event'});stay.changed();ambientAudio.triggerBell('quietBellAnomaly');}
 function update(dt){if(pending){nightDelay-=Math.min(.1,dt);if(nightDelay<=0){pending=false;begin();}}if(reactUntil<=0)return;reactUntil-=Math.min(.1,dt);elapsed+=dt;if(elapsed<.25)return;elapsed=0;for(const r of reactions){if(!r.object.visible||shopSystem.current)continue;const p=r.object.getWorldPosition(new THREE.Vector3());r.object.rotation.y=Math.atan2(22-p.x,-25-p.z);r.activity='listening';}}
 const shelf=catPassages.routes.find(r=>r.id==='cat-route-tavern')??catPassages.routes[0];
 const clue=new THREE.Object3D();clue.position.set(.18,.12,.23);shelf.object.add(clue);const vertices=[];for(let i=0;i<9;i++){const x=-.08+i*.02,y=.012,z=.0,l=.045+(i%3)*.01;vertices.push(x,y,z,x+.006,y,z,x,y,z+l,x+.006,y,z,x+.006,y,z+l,x,y,z+l);}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.computeVertexNormals();const scratch=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:0xa59a79,roughness:1,side:THREE.DoubleSide}));clue.add(scratch);scratch.userData.walkSoft=true;const show=()=>scratch.visible=!!t().anomalyDay;stay.onChange(show);show();
 const entry={id:'cat:bell-scratch',kind:'bell-cat',verb:'調べる',label:'木の裏の浅い傷',object:clue,range:1.5,profiles:['cat'],enabled:()=>!!t().anomalyDay};inspections.resolver.register(entry);
 inspections.handlers.set('bell-cat',e=>{inspections.present(e,{text:'雨と古い木の匂い。その下に、輪になりきらない傷がある。細い溝を、前足で九つ数えた。'});t().catFound=true;stay.data.discoveries[e.id]={day:stay.data.currentDay,period:townLife.state.period,playerMode:'cat',label:e.label};stay.note('bell-thread-cat','低い木の裏に、円になりきらない傷があった。',{kind:'cat',playerMode:'cat'});stay.changed();});
 dialogue.onSpeak(({character,text,profile})=>{if(profile==='human'&&/鐘/.test(text)&&!t().anomalyDay&&t().stage==='unseen'){t().stage='heard';stay.note('bell-thread-heard','最近、鐘の音が少し違う気がする、と聞いた。',{kind:'rumor'});stay.changed();}if(character.id==='starmaker'&&stay.data.currentDay>=2&&!t().anomalyDay){if(t().stage!=='linked')t().stage='chart';stay.changed();}});
 for(const c of dialogue.characters){const prior=c.eventReply;c.eventReply=args=>{const d=stay.data,night=t().anomalyDay===d.currentDay&&townLife.state.period==='night',after=t().anomalyDay&&d.currentDay>t().anomalyDay;if(args.index%3===1){if(c.id==='greenBard'&&args.profile==='cat'&&t().catFound)return '低いところにも、響きの跡は残るものだね。';if(night){if(c.id==='greenBard')return '今夜の鐘は、遠くまで届いたみたいだね。';if(c.id==='starmaker')return '今の間隔……星図の余白に、似た並びがあった気がします。';return '今の鐘、聞いた？　いつもより、少し遅かったね。';}if(after&&d.currentDay===t().anomalyDay+1&&args.profile==='human')return c.id==='baker'?'昨夜の鐘、聞いた？　でも窯は、いつもどおり温まっているよ。':'昨夜の鐘、聞きましたか。今日は、いつもの朝ですね。';if(d.currentDay>=2&&args.profile==='human'&&c.id==='starmaker')return '古い星図に、円と九つの点があります。星の並びとは、少し違うんです。';if(d.currentDay>=2&&args.profile==='human'&&c.id==='bookseller')return '似た図版を、古い本で見た気がします。向きまでは、覚えていません。';}return prior?.(args)??null;};}
 sync();return{update,entry,progress:()=>({...t(),...bellProgress(stay.data,townLife.state.period)}),get pending(){return pending}};
}
