import {createDetailBatch} from './miniature.js';
import {lakeWaterPhase} from './lake-water-level.js';
import {threadSnapshot,ringStage} from './story-thread-data.js';
export const ringLayout={id:'the-ring',center:[-403,4.8,-80],radius:14,entry:[-401,4.8,-66],bounds:{minX:-420,maxX:-386,minZ:-99,maxZ:-61},route:[[-350,5.44,-37],[-353,5.12,-42],[-357,4.92,-46],[-365,5.75,-48],[-377,5.75,-53],[-392,4.8,-59],[-401,4.8,-66]],future:[-405,4.2,-105]};
const lakebedRadius=a=>16+.35*Math.sin(a*3)+.2*Math.cos(a*7);
export const ringOpen=()=>lakeWaterPhase()==='extremeLow';
export function extensionReading(x,z){let best=null;for(let i=1;i<ringLayout.route.length;i++){const a=ringLayout.route[i-1],b=ringLayout.route[i],dx=b[0]-a[0],dz=b[2]-a[2],t=Math.max(0,Math.min(1,((x-a[0])*dx+(z-a[2])*dz)/(dx*dx+dz*dz))),distance=Math.hypot(x-a[0]-dx*t,z-a[2]-dz*t);if(!best||distance<best.distance)best={distance,height:a[1]+t*(b[1]-a[1]),segment:i,t};}return best;}
const local=(x,z)=>x>=-422&&x<=-348&&z>=-100&&z<=-34;
export function ringHeight(x,z){if(!ringOpen()||!local(x,z))return null;const q=extensionReading(x,z);if(q.distance<=1.55)return q.height;const dx=x+403,dz=z+80,r=Math.hypot(dx,dz);if(r<=lakebedRadius(Math.atan2(dz,dx)))return 4.8+.055*Math.sin(dx*.22)*Math.sin(dz*.19);return null;}
export function ringBoatBlocked(x,z,phase=lakeWaterPhase()){if(phase!=='extremeLow'||!local(x,z))return false;const q=extensionReading(x,z),bridge=q.segment===4&&q.t>.03&&q.t<.97;return(q.distance<2.8&&!bridge)||Math.hypot(x+403,z+80)<17.5;}
export function ringWallBlocked(x,z,y,profile){if(!ringOpen())return false;const r=Math.hypot(x+403,z+80);if(Math.abs(r-14)>.42+profile.radius)return false;const i=Math.round(((Math.atan2(z+80,x+403)+Math.PI*2)%(Math.PI*2))/Math.PI/2*48)%48;return !(i>=11&&i<=13||i>=28&&i<=39);}
export function buildTheRing({THREE,scene,box,lake}){
 const root=new THREE.Group();root.name='The Ring exposed lakebed';scene.add(root);root.visible=false;
 const stone=lake.materials.stone.clone();stone.color.setHex(0x6e7e7e);const mud=lake.materials.earth.clone();mud.color.setHex(0x657371);const moss=lake.materials.reeds,wood=lake.materials.wood;
 const details=new THREE.Group();details.name='The Ring nearby details';root.add(details);
 const targets=[],catSteps=[],gaps=[],p=[],floorY=(x,z)=>4.8+.055*Math.sin((x+403)*.22)*Math.sin((z+80)*.19);
 function tri(a,b,c){p.push(...a,...b,...c);}
 for(let i=1;i<ringLayout.route.length;i++){const a=ringLayout.route[i-1],b=ringLayout.route[i],dx=b[0]-a[0],dz=b[2]-a[2],l=Math.hypot(dx,dz),nx=-dz/l*1.55,nz=dx/l*1.55;const v=[a[0]+nx,a[1]-.03,a[2]+nz],w=[a[0]-nx,a[1]-.03,a[2]-nz],q=[b[0]+nx,b[1]-.03,b[2]+nz],r=[b[0]-nx,b[1]-.03,b[2]-nz];tri(v,q,r);tri(v,r,w);const bottom=i===4?5.55:3.9;for(const [c,d]of [[v,q],[r,w]]){tri(c,[c[0],bottom,c[2]],d);tri(d,[c[0],bottom,c[2]],[d[0],bottom,d[2]]);}}
 for(let i=0;i<64;i++){const a=i/64*Math.PI*2,b=(i+1)/64*Math.PI*2,v=[-403+Math.cos(a)*lakebedRadius(a),floorY(-403+Math.cos(a)*lakebedRadius(a),-80+Math.sin(a)*lakebedRadius(a))-.03,-80+Math.sin(a)*lakebedRadius(a)],w=[-403+Math.cos(b)*lakebedRadius(b),floorY(-403+Math.cos(b)*lakebedRadius(b),-80+Math.sin(b)*lakebedRadius(b))-.03,-80+Math.sin(b)*lakebedRadius(b)];tri([-403,4.77,-80],w,v);tri(v,w,[w[0],3.9,w[2]]);tri(v,[w[0],3.9,w[2]],[v[0],3.9,v[2]]);}
 const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.computeVertexNormals();const bed=new THREE.Mesh(g,mud);bed.receiveShadow=true;bed.userData.walkSoft=true;root.add(bed);
 const batch=createDetailBatch(THREE,root,'The Ring batched wet masonry');
 for(let i=1;i<ringLayout.route.length;i++){const a=ringLayout.route[i-1],b=ringLayout.route[i],dx=b[0]-a[0],dz=b[2]-a[2],n=Math.ceil(Math.hypot(dx,dz)),yaw=-Math.atan2(dz,dx);for(let j=0;j<n;j++){const t=(j+.5)/n;for(const k of [-.95,0,.95])batch.add('block',stone,[a[0]+dx*t+Math.sin(yaw)*k,a[1]+(b[1]-a[1])*t-.045,a[2]+dz*t+Math.cos(yaw)*k],[.77,.09,.8],yaw,new THREE.Color(j%3?0xd7dfda:0xbdcbc6));}}
 for(let i=0;i<9;i++){const a=i/8*Math.PI*1.45;batch.add('block',moss,[-409+Math.cos(a)*.22,4.86,-77+Math.sin(a)*.22],[.12,.012,.025],-a-Math.PI/2);}
 for(let i=0;i<3;i++)batch.add('block',moss,[-403+i*.07,4.855,-90+i*.11],[.025,.012,.22],.4);
 // Three quarters of a wall survive; the missing arc is foundations and debris.
 for(let i=0;i<48;i++){if(i>=11&&i<=13)continue;const a=i/48*Math.PI*2,x=-403+Math.cos(a)*14,z=-80+Math.sin(a)*14,h=i>=28&&i<=39?.12:.5+(i%7)*.24,y=floorY(x,z);batch.add('block',stone,[x,y+h/2,z],[1.55,h,.8],-a,new THREE.Color(i%4===0?0xbac8c5:0xd7dfd8));if(i%6===1)batch.add('leaf',moss,[x+.2,y+.08,z+.2],[.7,.12,.5]);}
 for(const a of [.3,1.5,2.6])for(let j=0;j<5;j++){const r=4+j*1.6;batch.add('block',stone,[-403+Math.cos(a)*r,4.83,-80+Math.sin(a)*r],[1,.035,.13],-a);}
 for(const [x,z]of [[-398,-79],[-409,-84],[-394,-85]])batch.add('block',lake.materials.water,[x,floorY(x,z)+.01,z],[1.1,.012,.65]);
 for(let i=0;i<5;i++)batch.add('block',stone,[-405,4.65-i*.2,-96-i*1.3],[2.1,.22,.65]);batch.finish();batch.root.traverse(o=>o.userData.walkSoft=true);
 const piece=(x,z,w,h,d,mat=stone,y=floorY(x,z))=>{const o=box(x,y-.04,z,w,h,d,mat,details);o.castShadow=false;return o;};
 const notice=(id,label,text,object,profiles=['human','cat'],point=[0,.2,0])=>{targets.push({id:'ring:'+id,label,text,kind:'inspect',object,profiles,range:2.7,localPoint:point});return targets.at(-1);};
 notice('outer','欠けた外周石','円は完全ではない。崩れたのか、最初からそうだったのかは分からない。',piece(-393,-73,.55,.4,.4));
 notice('pillar','低い柱','水跡が二重に残っている。上の縁には、湿った苔がついている。',piece(-402,-69,.55,1.1,.55));
 notice('groove','円になりきらない溝','溝は途中でずれている。Nine Stonesの並びと、同じ円には見えない。',piece(-409,-77,.7,.05,.5));
 notice('center','中央の浅い窪み','中央には浅い水だけが残っている。何かを置いていた跡かどうかも分からない。',piece(-403,-80,1.8,.025,1.2,lake.materials.water));
 notice('watermark','壁の水位線','この線より上まで、水は戻ることがあるのだろう。',piece(-414,-83,.6,.7,.5));
 notice('direction','湖を向く刻み','短い線は中央ではなく、湖の向こうを向いているようにも見える。',piece(-403,-90,.55,.07,.45));
 notice('beyond','沈んだ石段','石段は泥と水へ沈んでいる。向こうにも段があるようだが、足を置ける場所はない。',piece(-405,-94,.7,.08,.5));
 for(let i=0;i<4;i++){const x=i===2?-404:-393-i*5,z=i===2?-93:i%2?-86:-76,y=floorY(x,z),o=piece(x,z,1.1,.13,2,stone,y+.58);piece(x,z-.9,.16,.68,.16);piece(x,z+.9,.16,.68,.16);gaps.push({x,z,y,object:o});if(i<3)notice('cat-'+i,['石の裏の線','水跡の下の溝','奥から来る冷たい風'][i],['下面だけに、浅い刻みがある。泥の匂いが、線の中に残っている。','低い溝を鼻でたどる。輪ではなく、その外へ続いている。','暗い隙間の向こうに、もう一段。冷たい風だけが抜けてくる。'][i],o,['cat'],[0,-.22,0]);}
 for(let i=0;i<6;i++){const x=-394-i*3,z=i%2?-88:-72,o=piece(x,z,.8,.22+(i%2)*.08,.65);o.userData.walkSurface=true;catSteps.push(o);}
 for(const [id,x,z,eye,focus]of [['approach',-401,-66,[-383,22,-53],[-403,4.8,-80]],['high',-415,-75,[-418,23,-62],[-403,4.8,-80]]]){const o=piece(x,z,.6,.05,.5);const e=notice('view-'+id,'円環を眺める','沈んだ道の先に、大きな円が残っていた。欠けた部分まで、空が見える。',o,['human']);e.kind='quiet-view';e.verb='眺める';e.viewEye=eye;e.viewFocus=focus;}
 return{root,details,stone,mud,targets,catSteps,gaps,heightAt:ringHeight,layout:ringLayout};
}
export function ringRegion(stay){const found=()=>!!stay.data.discoveries['ring:visit'];const c=(id,name,eye,focus)=>({id:'ring-'+id,name,eye,focus,enabled:ringOpen});const t=(id,name,position)=>({id:'ring-'+id,name,short:name.slice(0,1),position,enabled:()=>found()&&ringOpen()});return{id:'the-ring',name:'The Ring',visitedFlags:['ring:visit'],description:'The Ring — 水の底に残った、不完全な円',conditional:true,contains:p=>p.y<5.4&&ringHeight(p.x,p.z)!==null,visible:found,enabled:ringOpen,walkingBounds:ringLayout.bounds,entryPoint:ringLayout.entry,mapBounds:ringLayout.bounds,ambientProfile:'hollow-lake-wind',cameraPresets:[c('overview','全景',[-381,28,-56],[-403,4.8,-80]),c('outer','外周',[-387,9,-72],[-402,5,-80]),c('center','中央',[-399,10,-73],[-403,5,-80]),c('entry','Drowned Way入口',[-401,12,-62],[-375,5,-48]),c('broken','崩れた側',[-417,10,-91],[-405,5,-92]),c('lake','Lake Lun方向',[-403,10,-80],[-321,6,-24]),c('caerith','Caerith方向',[-399,10,-78],[-371,8,-76])],navigationTargets:[t('entry','古道入口',ringLayout.entry),t('outer','円環',[-393,4.8,-73]),t('center','中央',[-403,4.8,-80]),{...t('end','石段',[-405,4.8,-94]),enabled:()=>ringOpen()&&!!stay.data.discoveries['ring:beyond']}]};}
export function connectTheRing({THREE,camera,getQuality=()=>'standard',ring,stay,level,walking,shopSystem,boatTravel,regions,inspections,quietStay,townLife,dialogue,ambientAudio}){
 let busy=false,elapsed=0,key='',soundDay=0;stay.data.threads.ring??={stage:'unseen'};
 const found=()=>!!stay.data.discoveries['ring:visit'];
 function remember(id,text){if(stay.data.discoveries[id])return;stay.data.discoveries[id]={day:stay.data.currentDay,period:stay.data.dayPhase,playerMode:walking.state.profile.id,label:id};stay.note(id,text,{kind:walking.state.profile.id==='cat'?'cat-discovery':'place',playerMode:walking.state.profile.id});stay.changed();}
 for(const e of ring.targets){e.enabled=()=>ringOpen()&&!shopSystem.current;inspections.resolver.register(e);}
 ambientAudio.zones.push({id:'ring-water',enabled:ringOpen,sourceId:'lake-water',area:'town',position:[-403,4.8,-80],radius:28,gain:.06,src:null},{id:'ring-wind',enabled:ringOpen,sourceId:'nine-wind',area:'town',position:[-403,5,-80],radius:22,gain:.04,src:null});
 function updateDetails(){ring.details.visible=ringOpen()&&(regions.current.id==='the-ring'||!camera||Math.hypot(camera.position.x+403,camera.position.z+80)<(getQuality()==='mobile'?60:85));}
 function sync(){if(busy)return;busy=true;try{ring.root.visible=ringOpen();updateDetails();ring.stone.color.setHex(townLife.state.weather==='rain'?0x596e71:0x6e7e7e);const d=stay.data,t=d.threads.ring??={stage:'unseen'},stage=ringStage(d,ringOpen());if(t.stage!==stage){t.stage=stage;stay.changed();}const next=found()+':'+ringOpen();if(key!==next){key=next;regions.refresh();if(regions.current.id==='the-ring')regions.refreshArea();}}finally{busy=false;}}
 inspections.onPresent(({entry,text})=>{if(!entry.id.startsWith('ring:'))return;remember(entry.id,text);if(entry.id==='ring:groove'&&['nine:stone-3','nine:stone-5','nine:stone-9'].some(id=>stay.data.discoveries[id]))stay.note('ring:comparison','Nine Stonesと同じ形ではない。それでも、間隔には似たところがある。');if(entry.id==='ring:outer'&&stay.data.discoveries['caerith:foundation'])stay.note('ring:caerith','Caerithの基礎より大きい。でも、石の継ぎ方は少し似ていた。');if(entry.id==='ring:direction'&&stay.data.threads.bell?.anomalyDay)stay.note('ring:bell','あの夜の鐘を思い出した。ここで聞こえる風と、同じ響きだとは言えない。');sync();});
 const lines={greenBard:'まだ残っていたんだ。水の底は、忘れるのが上手いからね。',starmaker:'点の間隔は違う。でも円と線の向きは、星図と比べられそうです。',bookseller:'似た円形図はある。でも、注釈だけが抜け落ちているんだ。',lunHost:'旅人が、大きな円の話をしていたことがあるよ。岸が広い朝だったね。',lunBoat:'今日はずいぶん引いている。あの浅い石のところへは、舟を入れないで。',lunWatcher:'昔、年寄りが話していたよ。水が低い年には、輪のような石が見えたって。'};
 for(const c of dialogue.characters){const previous=c.eventReply;c.eventReply=args=>{if(stay.data.threads.bell?.anomalyDay===stay.data.currentDay&&townLife.state.period==='night')return previous?.(args);if(args.index%3===0&&lines[c.id]&&(found()||ringOpen()&&c.id.startsWith('lun')))return lines[c.id];return previous?.(args);};}
 const previousView=inspections.handlers.get('quiet-view');inspections.handlers.set('quiet-view',entry=>{previousView?.(entry);if(entry.id.startsWith('ring:view-')&&walking.state.profile.id==='human')remember('ring:shape','離れて立つと、欠けた石の並びが一つの大きな輪に見えた。');});
 stay.onChange(sync);level.onChange(sync);townLife.onChange(sync);sync();
 return{sync,remember,threads:()=>threadSnapshot(stay.data),update(dt){elapsed+=dt;if(elapsed<.5)return;elapsed=0;updateDetails();if(!ringOpen()||!walking.active||boatTravel.active||shopSystem.current)return;const p=walking.state.feet;if(p.y<5.4&&Math.hypot(p.x+403,p.z+80)<16){if(!found()){remember('ring:visit','沈んだ道の先に、大きな円が残っていた。');remember('region:the-ring','水が戻れば、ここはまた湖の下へ消える。');}if(soundDay!==stay.data.currentDay&&Math.hypot(p.x+403,p.z+80)<7&&townLife.state.weather==='fog'&&ambientAudio.stats.enabled&&ambientAudio.context?.state==='running'){soundDay=stay.data.currentDay;ambientAudio.stoneResonance();remember('ring:sound','低い響きが、石の間に残った。風が抜けたのかもしれない。');}}}};
}
