import {watercourseLayout} from './waterways.js';
import {townEventDefinitions,rumorPools} from './shop-data.js';
// Extends the shared resolver/card. No extra quest HUD or polling loop.
export function createTownEvents({THREE,scene,culture,inspectTargets,inspections,walking,townLife,shopSystem,dialogue,stay=null}){
 const entries=[],discoveries=new Map(Object.entries(stay?.data.discoveries??{}).filter(([id])=>townEventDefinitions.some(e=>e.id===id))),states=new Map(townEventDefinitions.map(e=>[e.id,{state:'unseen',heardAt:null,noticedAt:null,resolvedAt:null,...stay?.data.events?.[e.id]}])),props=[];let deliveryBag=null;const returnedRooms=new WeakSet();
 const stoneRumor='あの石の線は、流れが変わると一本増えて見えるそうだ。数えた者は、黙って戻ってきたよ。';
 function save(){if(!stay)return;for(const [id,e]of states)stay.data.events[id]={...e};for(const [id,e]of discoveries)stay.data.discoveries[id]={...e,day:e.day??townLife.state.dayIndex};stay.changed();}
 function roomChanges(room){const grain=states.get('delayed-grain'),book=states.get('missing-folio');if(room.shop.id==='bakery'&&grain.state==='resolved'&&!room.userDataGrain){const bag=new THREE.Mesh(new THREE.SphereGeometry(.17,7,5),room.materials.linen);bag.scale.set(1,1.2,.8);bag.position.set(-2.95,.204,-3.3);room.root.add(bag);bag.name='翌朝に届いた小麦袋';room.policy.obstacles.push({object:bag,bounds:new THREE.Box3().setFromObject(bag,true),isFloor:false});room.userDataGrain=bag;}if(room.shop.id==='bookshop'&&book.state==='resolved'&&townLife.state.dayIndex>(book.resolvedDay??1)&&!returnedRooms.has(room)){for(const o of room.hiddenBookObjects??[])o.visible=false;const target=room.inspect.find(e=>e.id==='inside:bookshop:hidden-book');if(target)target.enabled=()=>false;const found=new THREE.Mesh(new THREE.BoxGeometry(.10,.30,.08),room.materials.accent);found.position.set(2.4,1.27,-3.7);found.name='棚へ戻った薄い本';room.root.add(found);returnedRooms.add(room);book.returnedDay??=townLife.state.dayIndex;stay?.note('book-returned','昨日の薄い本が、古書店の棚へ戻っていた。',{kind:'event'});save();}}
 shopSystem.onRoom(roomChanges);
 for(const event of townEventDefinitions){if(!event.enabled)continue;
  const original=inspectTargets.find(q=>q.id===event.source),object=original?.object??culture.goods.find(o=>o.name===event.source);
  if(!object)throw Error('Missing town event source '+event.source);
  object.updateWorldMatrix(true,true);const b=new THREE.Box3().setFromObject(object,true),center=b.getCenter(new THREE.Vector3());center.y=b.min.y+.3;
  // Tiny tangible clues attach to the already-grounded goods/water system.
  // Their silhouettes stay below the walker's step allowance; no new blockers.
  if(['cat-bread','cat-ribbon','ninth-bell','upstream-stone'].includes(event.id)){
   const clue=event.id==='upstream-stone'?new THREE.Mesh(new THREE.IcosahedronGeometry(.085,0),culture.tools.materials.stone):event.id==='ninth-bell'?new THREE.Mesh(new THREE.CylinderGeometry(.055,.040,.10,6),culture.tools.materials.wood):new THREE.Mesh(new THREE.BoxGeometry(event.id==='cat-bread'?.085:.19,.018,.025),culture.tools.materials.linen);
   const at=event.id==='upstream-stone'?new THREE.Vector3(...watercourseLayout.stone):event.id==='ninth-bell'?new THREE.Vector3(center.x,b.max.y+.05,center.z):new THREE.Vector3(b.max.x+.055,b.min.y+.012,center.z-.12);
   clue.name=event.label;clue.position.copy(object.worldToLocal(at));clue.userData.walkSoft=true;object.add(clue);props.push(clue);
  }
  let interactive=object,localPoint=event.id==='upstream-stone'?object.worldToLocal(new THREE.Vector3(...watercourseLayout.stone)).toArray():original?.localPoint??object.worldToLocal(center.clone()).toArray();
  if(['loose-cart-wheel','late-cask','moved-cloth','absent-skiff','inn-parcel','cat-old-key'].includes(event.id)){const at=event.id==='absent-skiff'?new THREE.Vector3(center.x+1.1,b.min.y,center.z-.85):new THREE.Vector3(b.max.x+.35,b.min.y,center.z+.35);const floor=walking.groundAt(at.x,at.z,Infinity,walking.profiles.cat);at.y=(floor??b.min.y)+.045;const clue=new THREE.Mesh(new THREE.BoxGeometry(.15,.05,.12),culture.tools.materials.wood);clue.name=event.label;clue.userData.walkSoft=true;clue.position.copy(object.worldToLocal(at));object.add(clue);interactive=clue;localPoint=[0,.045,0];props.push(clue);}
  const entry={id:'event:'+event.id,kind:'town-event',verb:'調べる',label:event.label,object:interactive,localPoint,profiles:event.profiles??['human','cat'],range:3.2,priority:event.id==='upstream-stone'?-.30:.25,event,
   enabled:()=>!shopSystem.current&&(states.get(event.id).state==='resolved'||!event.periods||event.periods.includes(townLife.state.period))};
  inspections.resolver.register(entry);entries.push(entry);
 }
 inspections.handlers.set('town-event',entry=>{const playerMode=walking.state.profile.id,event=entry.event;
  const progress=states.get(event.id);progress.state=progress.state==='resolved'||event.id==='missing-folio'&&playerMode==='cat'&&shopSystem.current?'resolved':'noticed';progress.noticedAt=townLife.state.period;progress.noticedDay??=townLife.state.dayIndex;if(progress.state==='resolved'){progress.resolvedAt??=townLife.state.period;progress.resolvedDay??=townLife.state.dayIndex;}
  if(event.id==='unaddressed-crate'&&states.get('delayed-grain').state==='heard'){const grain=states.get('delayed-grain');grain.state='noticed';grain.noticedAt=townLife.state.period;grain.noticedDay=townLife.state.dayIndex;}
  discoveries.set(event.id,{id:event.id,playerMode,period:townLife.state.period,day:townLife.state.dayIndex,location:event.area});
  const message=event.resolvedText&&progress.state==='resolved'?event.resolvedText:event.id==='missing-folio'&&progress.state==='resolved'?'薄い本を見つけた。机の方で、紙を置く音がした。':event.id==='delayed-grain'&&progress.resolvedAt?'袋は届いている。新しい紐には、港の湿った匂いが残る。':event.text;
  save();inspections.present(entry,{text:playerMode==='cat'&&event.kind!=='cat-discovery'&&!(event.id==='missing-folio'&&progress.state==='resolved')?'木と紙に、何人もの手の匂いが重なっている。隙間には、風が少し残る。':message});
 });
 dialogue.onSpeak(({character,text,profile,time})=>{if(profile!=='human'||!character.rumorPool?.includes(text))return;let changed=false;for(const e of entries)if(e.event.rumorIds?.includes(character.id)||e.event.id==='upstream-stone'&&text===stoneRumor){const s=states.get(e.event.id);if(s.state==='unseen'){s.state='heard';s.heardAt=time;s.heardDay=townLife.state.dayIndex;changed=true;}}if(changed)save();});
 const baker=dialogue.characters.find(c=>c.id==='baker'),bookseller=dialogue.characters.find(c=>c.id==='bookseller');
 baker.eventReply=({profile,index})=>profile==='human'&&index%2===1&&states.get('delayed-grain').state==='resolved'?'小麦袋は届いたよ。明日の窯も、いつもの時刻に火を入れられる。':null;
 bookseller.eventReply=({profile,index})=>index%2===1&&states.get('missing-folio').state==='resolved'?(townLife.state.dayIndex>(states.get('missing-folio').resolvedDay??1)?profile==='cat'?'あの本は棚に戻したよ。今日は窓辺で休んでおいで。':'昨日は、薄い本のことを気にかけてくれてありがとう。今朝、棚へ戻しておきました。':profile==='cat'?'あの本を見つけたのは君かい。棚の下は、君の方がよく知っているね。':'薄い本は見つかりました。棚の下に、そっと戻っていたんですよ。'):null;
 function apply(){for(const def of townEventDefinitions){const progress=states.get(def.id);if(def.settlesAfter&&['noticed','heard'].includes(progress.state)&&townLife.state.dayIndex>=(progress.noticedDay??progress.heardDay??9999)+def.settlesAfter){progress.state='resolved';progress.resolvedDay=townLife.state.dayIndex;progress.resolvedAt=townLife.state.period;save();stay?.note('settled:'+def.id,def.resolvedText,{kind:'event'});}}const grain=states.get('delayed-grain');if(townLife.state.dayIndex>(grain.heardDay??9999)&&['heard','noticed'].includes(grain.state)){grain.state='resolved';grain.resolvedAt=townLife.state.period;grain.resolvedDay=townLife.state.dayIndex;save();stay?.note('grain-arrived','パン屋へ、昨日待っていた小麦袋が届いていた。',{kind:'event'});}if(grain.state==='resolved'){const cargo=entries.find(e=>e.event.id==='delayed-grain').object;if(!deliveryBag){deliveryBag=new THREE.Mesh(new THREE.SphereGeometry(.17,7,5),culture.tools.materials.linen);deliveryBag.scale.set(1,1.1,.8);deliveryBag.position.set(.27,.587,-.02);deliveryBag.userData.walkSoft=true;cargo.add(deliveryBag);props.push(deliveryBag);}entries.find(e=>e.event.id==='delayed-grain').label='届いた小麦袋';}for(const room of shopSystem.rooms.values())roomChanges(room);for(const character of dialogue.characters){const additions=entries.filter(e=>e.event.rumorIds?.includes(character.id)&&(!e.event.periods||e.event.periods.includes(townLife.state.period))).map(e=>e.event.rumor);character.rumorPool=[...(rumorPools[character.id]??[]),...additions];if(character.id==='baker'&&grain.state==='resolved')character.rumorPool=['今朝の粉は、新しい袋を開けたものだよ。昨日の港の匂いが、まだ少し残っている。'];if(character.id==='bookseller'&&states.get('missing-folio').state==='resolved')character.rumorPool=[];if(character.id==='boatworker'&&townLife.state.dayIndex>=2)character.rumorPool.push(stoneRumor);}}

 townLife.onChange(apply);apply();
 return {entries,discoveries,states,get stats(){return {observations:entries.length,catOnly:entries.filter(e=>e.profiles.length===1&&e.profiles[0]==='cat').length,discovered:discoveries.size,addedLights:0,addedMeshes:props.length};}};
}
