import {createDetailBatch} from './miniature.js';
import {mireLayout as L,mireCharacters,mireIncidents,mireSeasonProfiles,regionalAtmospheres} from './violet-mire-data.js';
import {evaluateConditions} from './progression-data.js';
import {crownOpen} from './hollow-crown.js';
import {regionActivity} from './region-activity.js';
export {mireLayout} from './violet-mire-data.js';
let unlocked=false,royalExtended=false;
export const extendRoyalRoad=v=>royalExtended=!!v;
export const setMireUnlocked=v=>unlocked=!!v;
export const mireOpen=()=>unlocked;
export function pathReading(points,x,z){let best={distance:Infinity};for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],dx=b[0]-a[0],dz=b[2]-a[2],t=Math.max(0,Math.min(1,((x-a[0])*dx+(z-a[2])*dz)/(dx*dx+dz*dz))),d=Math.hypot(x-a[0]-dx*t,z-a[2]-dz*t);if(d<best.distance)best={distance:d,height:a[1]+(b[1]-a[1])*t};}return best;}
const bedY=(x,z)=>4.5+.025*Math.sin((x+458)*.3)*Math.sin((z+216)*.22);
const inMire=(x,z)=>((x+458)/26)**2+((z+216)/35)**2<1;
const deep=(x,z)=>L.pools.some(p=>((x-p.x)/p.rx)**2+((z-p.z)/p.rz)**2<1);
export function mireHeight(x,z){if(!unlocked)return null;const boarding=pathReading(L.boardwalk,x,z);if(boarding.distance<1.35)return boarding.height;const transition=pathReading(L.transition,x,z);if(z>-183.5&&transition.distance<1.25)return crownOpen()?transition.height:null;const b=pathReading(L.boardwalk,x,z),r=pathReading(L.royalRoad,x,z);if(b.distance<1.35)return b.height;if(r.distance<1.2)return r.height;if(inMire(x,z)&&!deep(x,z))return bedY(x,z);return null;}
export const mireDryVolume=(x,z,y)=>mireHeight(x,z)!==null&&y<6;
export function mireBlocked(x,z,y,profile){if(!unlocked)return false;if(inMire(x,z)&&deep(x,z)&&pathReading(L.boardwalk,x,z).distance>1.35)return true;const r=pathReading(L.royalRoad,x,z);return !royalExtended&&z<-248.1&&x<-476&&r.distance<2;}
export const mireCleft=(x,z)=>unlocked&&crownOpen()&&z<-151&&z>-160&&x<-417&&pathReading(L.transition,x,z).distance<1.3;
export function buildVioletMire({THREE,scene,box,residentScale,lake}){
 const root=new THREE.Group();root.name='Violet Mire';root.visible=false;scene.add(root);const details=new THREE.Group();root.add(details);
 const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:1}),earth=mat(0x666a57),wood=mat(0x5b584a),repair=mat(0x8a8570),stone=mat(0x687677),grass=mat(0x697f65),flower=mat(0x8d8295),water=mat(0x455e5b);water.roughness=.97;const materials={earth,wood,stone,grass,flower,water,repair};
 const batch=createDetailBatch(THREE,root,'Mire instanced trees roots flowers and paving');const pos=[];const tri=(a,b,c)=>pos.push(...a,...b,...c);
 function strip(points,w){for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],dx=b[0]-a[0],dz=b[2]-a[2],len=Math.hypot(dx,dz),nx=-dz/len*w/2,nz=dx/len*w/2,v=[a[0]+nx,a[1]-.035,a[2]+nz],q=[a[0]-nx,a[1]-.035,a[2]-nz],r=[b[0]+nx,b[1]-.035,b[2]+nz],t=[b[0]-nx,b[1]-.035,b[2]-nz];tri(v,r,t);tri(v,t,q);}}
 batch.add('block',repair,[-440,4.56,-183],[3.1,.12,3.1]);strip(L.transition,3.1);for(let i=0;i<72;i++){const a=i/72*Math.PI*2,b=(i+1)/72*Math.PI*2,ra=1.04+.025*Math.sin(a*3)+.015*Math.sin(a*7),rb=1.04+.025*Math.sin(b*3)+.015*Math.sin(b*7),v=[-458+Math.cos(a)*26*ra,bedY(-458+Math.cos(a)*26*ra,-216+Math.sin(a)*35*ra),-216+Math.sin(a)*35*ra],w=[-458+Math.cos(b)*26*rb,bedY(-458+Math.cos(b)*26*rb,-216+Math.sin(b)*35*rb),-216+Math.sin(b)*35*rb];tri([-458,4.5,-216],w,v);tri(v,[v[0],2.1,v[2]],w);tri(w,[v[0],2.1,v[2]],[w[0],2.1,w[2]]);}strip(L.royalRoad,3);
 // Quiet far wetland banks keep the basin part of a wider landscape.
 for(let i=0;i<48;i++){const a=i/48*Math.PI*2,b=(i+1)/48*Math.PI*2,v=[-466+Math.cos(a)*(62+5*Math.sin(a*3)),4.2,Math.min(-184,-222+Math.sin(a)*(55+3*Math.sin(a*5)))],w=[-466+Math.cos(b)*(62+5*Math.sin(b*3)),4.2,Math.min(-184,-222+Math.sin(b)*(55+3*Math.sin(b*5)))];tri([-466,4.2,-222],w,v);}for(let i=0;i<64;i++){const a=i/64*Math.PI*2,x=-458+Math.cos(a)*26.3,z=-216+Math.sin(a)*35.3;if(pathReading(L.transition,x,z).distance<3||pathReading(L.boardwalk,x,z).distance<3||pathReading(L.royalRoad,x,z).distance<3)continue;batch.add('leaf',grass,[x,4.9,z],[1.5,.65,1.3]);batch.add('block',wood,[x,4.7,z],[1.1,.25,.15],-a);}for(const[x,z,w,d]of[[-457,-209,2.3,1.1],[-463,-233,2.1,.8],[-440,-195,1.3,.7],[-473,-236,2,1]])batch.add('block',water,[x,4.51,z],[w,.012,d]);
 const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.computeVertexNormals();const bed=new THREE.Mesh(geo,earth);root.add(bed);bed.userData.walkSoft=true;
 // Narrow low boardwalks: visible surfaces agree with the analytic support.
 for(const points of [L.transition,L.boardwalk,L.royalRoad])for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],dx=b[0]-a[0],dz=b[2]-a[2],l=Math.hypot(dx,dz),yaw=-Math.atan2(dz,dx),n=Math.ceil(l/.7);for(let j=0;j<n;j++){const t=(j+.5)/n,x=a[0]+dx*t,z=a[2]+dz*t,y=a[1]+(b[1]-a[1])*t,transition=points===L.transition,royal=points===L.royalRoad;batch.add('block',transition||royal?stone:j%13===0?repair:wood,[x,y-.06,z],[2.65,.12,.68],yaw);if(!transition&&!royal&&j%5===0)for(const sign of[-1,1])batch.add('block',wood,[x-dz/l*sign*1.15,4.36,z+dx/l*sign*1.15],[.13,.35,.13]);if(transition&&j%4===0)batch.add('leaf',grass,[x+1.65,y+.12,z],[.5,.14,.35]);}}
 // Roots and low banks border a few visibly deeper pools, not invisible fencing.
 for(const p of L.pools){const mesh=new THREE.Mesh(new THREE.CircleGeometry(1,24),water);mesh.rotation.x=-Math.PI/2;mesh.scale.set(p.rx*1.12,p.rz*1.12,1);mesh.position.set(p.x,4.49,p.z);mesh.userData.walkSoft=true;root.add(mesh);for(let i=0;i<16;i++){const a=i/16*Math.PI*2;batch.add('leaf',grass,[p.x+Math.cos(a)*p.rx*1.07,4.67,p.z+Math.sin(a)*p.rz*1.07],[.35,.34,.3]);}}
 for(let i=0;i<80;i++){const a=i*2.39996,r=9+(i%7)*2.1,x=-458+Math.cos(a)*r,z=-216+Math.sin(a)*r*1.4;if(pathReading(L.boardwalk,x,z).distance<2.5||deep(x,z))continue;batch.add('leaf',grass,[x,4.64,z],[.8,.25,.65]);if(i%7===0){const h=2.6+i%3*.5;batch.add('block',wood,[x,4.5+h/2,z],[.13,h,.13]);batch.add('leaf',grass,[x,4.5+h,z],[.7,.8,.6]);}if(i%4===0)batch.add('leaf',flower,[x+.3,4.71,z+.2],[.09,.09,.09]);}
 for(let i=0;i<12;i++){const t=i/11,x=-424-12*t,z=-158-18*t;batch.add('leaf',stone,[x+2,2.6+1.2*t,z],[1.3,1.1,.9]);batch.add('block',wood,[x,2.4+1.1*t,z],[1.8,.12,.2],-.5);}
 // Dry rest shelter, small work traces, and a better-paved road beyond the mire.
 for(const x of[-474,-470])for(const z of[-226,-230])batch.add('block',wood,[x,5.6,z],[.13,2.2,.13]);batch.add('block',wood,[-472,6.78,-228],[4.8,.16,4.8]);batch.add('block',wood,[-472,4.86,-228],[3.2,.7,1]);batch.add('leaf',stone,[-475,4.7,-232],[.65,.2,.5]);
 for(let i=0;i<5;i++)batch.add('leaf',stone,[-483+(i%2)*.7,5.32,-247-i*.8],[.7,.45,.6]);batch.finish();
 const flood=box(-437,4.5,-178,3.4,.025,7,water,root);flood.userData.walkSoft=true;flood.visible=false;
 const targets=[],catSteps=[],routes=[];const marker=(x,z,w=.35,h=.12,d=.3)=>{const y=x>-438&&z>-182?pathReading(L.transition,x,z).height:bedY(x,z);const o=box(x,y-.025,z,w,h,d,stone,details);o.userData.walkSoft=true;return o;};
 const notice=(id,label,text,x,z,profiles=['human','cat'],kind='inspect')=>{const e={id:'mire:'+id,label,text,object:marker(x,z),localPoint:[0,.16,0],range:2.8,profiles,kind};targets.push(e);return e;};
 for(const q of [
 ['boardwalk','継ぎ足した木道','明るい板と暗い板が交互に残る。道は、少しずつ直されてきたらしい。',-446,-194],['flower','湿地の花','薄紫は花の先にだけ残る。根は、水より少し高い泥にある。',-443,-190],['stone','泥に沈む石','青灰の石に、Hollow Crownの壁と似た白い筋がある。',-448,-198],['surface','小さな水面','枝の間に空が映る。顔を動かすと、空いたところの形も変わる。',-453,-213],['post','古い杭','杭の向きは木道と少しずれている。水跡は、上まで続いていない。',-463,-218],['roots','根の分かれる場所','根の間に乾いた足跡が続く。湿地は一面の水ではない。',-470,-224],['reflection','空の反射','水に映る空と、杭の間の線が重なって見える。星図と同じとは、まだ言えない。',-460,-233],['sign','古い道標','Caer Veyra。小さい字だけが残る。先の石道は、壊れた橋へ続いている。',-476,-245]])notice(...q);
 for(const e of mireIncidents){const q=notice(e.id.slice(5),e.label,e.text,e.position[0],e.position[2],['human','cat'],'mire-incident');q.incident=e;}
 for(const[id,x,z,focus]of[['basin',-443,-184,[-460,4.8,-216]],['hollow',-469,-235,[-456,5,-218]]]){const e=notice('view-'+id,'湿地を眺める','木道の先で、水と草が細かく分かれている。',x,z,['human','cat'],'quiet-view');Object.assign(e,{verb:'眺める',viewEye:[x,6.3,z],viewFocus:focus});}
 for(let i=0;i<5;i++){const x=[-442,-453,-468,-461,-475][i],z=[-189,-202,-221,-229,-233][i],y=bedY(x,z);const o=box(x,y+.65,z,1.6,.14,.25,wood,details);o.userData.walkSoft=true;for(const dx of[-.72,.72]){const post=box(x+dx,y,z,.12,.68,.25,wood,details);post.userData.walkSoft=true;}routes.push({id:'mire-gap-'+i,start:[x,y,z-1],end:[x,y,z+1],center:[x,y,z],object:o});if(i<3)notice('cat-'+i,['古い布の端','木の穴の風','薄紫の花びら'][i],['根の間に、小さな布が引っかかっている。雨と人の匂いが残る。','木の穴から、冷たい風。石の空洞より、草の匂いが濃い。','倒れた枝に、花びらが一枚。刻まれた印とは違う、軽い跡だ。'][i],x,z,['cat']);}
 for(let i=0;i<7;i++){const x=-445-(i%4)*7,z=-196-Math.floor(i/4)*28,o=marker(x,z,.75,.24,.6);o.userData.walkSurface=true;catSteps.push(o);}
 const sign=marker(-476,-245,.7,.85,.2);sign.material=wood;const canvas=document.createElement('canvas');canvas.width=256;canvas.height=64;const ctx=canvas.getContext('2d');ctx.fillStyle='#9d9784';ctx.fillRect(0,0,256,64);ctx.fillStyle='#484b43';ctx.font='26px Georgia';ctx.fillText('Caer Veyra',20,41);const label=new THREE.Mesh(new THREE.PlaneGeometry(1.65,.42),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(canvas)}));label.position.set(-476,5.54,-244.88);root.add(label);label.userData.walkSoft=true;
 const people=[],actors={},localPaths={'mire-hub':[[-469,4.5,-228]],'mire-shelter':[[-469,4.5,-228],[-470,4.5,-227]],'mire-flowers':[[-469,4.5,-228],[-464,4.62,-216],[-456,4.62,-203],[-446,4.62,-194],[-442,4.5,-187]],'mire-repair':[[-469,4.5,-228],[-464,4.62,-216],[-456,4.62,-203],[-451,4.5,-199]],'mire-exit-watch':[[-469,4.5,-228],[-464,4.62,-216],[-456,4.62,-203],[-446,4.62,-194],[-441.1,4.62,-183.5],[-439.8,4.62,-182.1]]};
 for(let i=0;i<3;i++){const o=new THREE.Group();root.add(o);const cloth=mat([0x697969,0x77705e,0x626b72][i]),skin=mat(0xb29379),body=new THREE.Mesh(new THREE.CylinderGeometry(.24,.34,1.05,8),cloth),head=new THREE.Mesh(new THREE.SphereGeometry(.23,8,6),skin);body.position.y=.65;head.position.y=1.42;o.add(body,head);o.userData.community=true;o.userData.appearanceIndex=14+i;o.userData.visitorRole={activity:i===0?'browsing':i===1?'rope':'resting',posture:i===1?'working':'relaxed',prop:i===1?'tools':null,hair:[0x6a6255,0x4a493e,0x7b7462][i],accent:0x839080};o.position.set(-470+i*1.6,4.5,-230);residentScale.normalize(o,{head});o.name=mireCharacters[i]?.name??'湿地を通る旅人';people.push({object:o,index:i});localPaths['mire-home-'+i]=[[-469,4.5,-228],[-470+i*1.6,4.5,-230]];if(i<2)actors[mireCharacters[i].id]=o;}
 root.traverse(o=>{if(o.isMesh){o.castShadow=false;o.userData.walkSoft=true;}});const flowers=[],plants=[];root.traverse(o=>{if(o.isInstancedMesh&&o.material===flower){o.userData.maximumCount=o.count;flowers.push(o);}if(o.isInstancedMesh&&o.material===grass)plants.push(o);});const plantBases=plants.map(o=>Array.from({length:Math.min(8,o.count)},(_,i)=>{const m=new THREE.Matrix4();o.getMatrixAt(i,m);return m;}));
 return{flood,flowers,plants,plantBases,root,detailBatch:batch.root,details,materials,targets,catSteps,routes,people,actors,localPaths,heightAt:mireHeight,layout:L,waterPools:L.pools};
}
export function mireRegion(stay){const found=()=>!!stay.data.discoveries['mire:visit']||!!stay.data.discoveries['region:violet-mire'],c=(id,name,eye,focus)=>({id:'mire-'+id,name,eye,focus}),t=(id,name,p)=>({id:'mire-'+id,name,short:name.slice(0,1),position:p});return{id:'violet-mire',name:'Violet Mire',visitedFlags:['mire:visit'],description:'Violet Mire — 木道と薄い霧、湿った静けさ',conditional:true,visible:found,enabled:mireOpen,contains:p=>mireHeight(p.x,p.z)!==null&&p.z<-182.5,walkingBounds:L.bounds,entryPoint:L.entry,mapBounds:L.bounds,ambientProfile:'wetland-quiet',cameraPresets:[c('overview','全景',[-426,24,-177],[-458,4.5,-216]),c('entry','入口',[-433,8,-178],[-442,5,-189]),c('boardwalk','木道',[-447,8,-198],[-461,5,-215]),c('basin','中央湿地',[-451,11,-215],[-464,5,-215]),c('hollow','Violet Hollow',[-456,9,-228],[-467,5,-237]),c('shelter','休憩小屋',[-462,9,-218],[-472,5,-228]),c('road','Caer Veyra方面',[-466,9,-237],[-479,6,-249])],navigationTargets:[t('entry','Hollow Crown方面',L.entry),t('boardwalk','木道',[-456,4.62,-203]),t('shelter','休憩小屋',[-469,4.5,-228]),t('hollow','奥の窪地',[-468,4.62,-237])]};}
export function connectVioletMire({THREE,mire,crown,stay,walking,inspections,regions,dialogue,townLife,ambientAudio,residentLife,residentDay,camera,scene,getQuality=()=>'standard'}){
 const seen=id=>!!stay.data.discoveries[id];let elapsed=0,busy=false,lastWeather=null,lastSeason=null,lastAvailable=null,originalFog=null,plantTime=0;const controllers=[];
 const remember=(id,text,kind='place')=>{if(seen(id))return false;stay.data.discoveries[id]={day:stay.data.currentDay,period:stay.data.dayPhase,playerMode:walking.state.profile.id,label:id};stay.note(id,text,{kind:walking.state.profile.id==='cat'?'cat-discovery':kind,playerMode:walking.state.profile.id});stay.changed();return true;};
 const old=inspections.resolver.entries.get('crown:crack');old.kind='mire-exit';old.verb='外気を確かめる';inspections.handlers.set('mire-exit',e=>{if(!evaluateConditions('mire-exit',stay.data)){inspections.present(e,{text:'根の絡む裂け目の先に、湿った外気がある。足元の石を、もう少し確かめてからにしよう。'});return;}remember('mire:exit','石の裂け目の先で、湿った草の匂いがした。根の間に、外へ続く道がある。');inspections.present(e,{text:'水が引いた下に、湿った坂が続いている。石の白い筋は、外の根に隠れていく。'});sync();});
 for(const e of mire.targets){e.enabled=()=>mireOpen()&&(e.kind!=='mire-incident'||e.incident.cycle.includes((stay.data.currentDay-1)%7));inspections.resolver.register(e);}for(const q of mire.routes)walking.registerObstacle(q.object);
 inspections.onPresent(({entry,text})=>{if(!entry.id.startsWith('mire:'))return;remember(entry.id,text??entry.text,entry.kind==='mire-incident'?'event':'place');});inspections.handlers.set('mire-incident',e=>{inspections.present(e,{text:e.text});const state=stay.data.events[e.id]??={state:'noticed'};state.noticedDay=stay.data.currentDay;stay.changed();});
 for(const {object,index:i}of mire.people){const record=residentLife.records.find(r=>r.object===object);controllers.push(residentDay.addScheduled(record,{id:'mire-person-'+i,regionId:'violet-mire',chooseDestination:({day,period})=>i===1&&day%7===1&&period==='day'&&crownOpen()?'mire-exit-watch':null,home:'mire-home-'+i,schedule:{morning:i===0?'mire-flowers':i===1?'mire-repair':'mire-shelter',day:i===0?'mire-flowers':i===1?'mire-repair':'mire-shelter',evening:'mire-shelter',night:'home'},shelter:'mire-shelter',dawnPlace:'mire-shelter',present:i===2?()=>mireOpen()&&crownOpen()&&stay.data.currentDay%9===0&&!['rain','night','blackout'].includes(townLife.state.weather):()=>mireOpen()}));}
 const traveler=mire.people[2].object;inspections.resolver.register({id:'mire:traveler',kind:'mire-traveler',verb:'話す',label:'湿地を通る旅人',object:traveler,localPoint:[0,1.2,0],range:3,profiles:['human','cat'],enabled:()=>traveler.visible&&mireOpen()});inspections.handlers.set('mire-traveler',e=>{const text='石道の方は、もう少し広い。けれど橋の向こうは、今日は渡れなかったよ。';inspections.present(e,{text});remember(e.id,text,'person');});
 const lines={greenBard:'ここは、昔から道を迷わせるのが上手い。水に映る空ばかり見ているとね。',starmaker:'杭と水面の線は、星図と重ねて考えられます。でも、見ている向きで変わるものもあります。',bookseller:'湿った道の記録は少ない。紙が残りにくかったのか、書かなかったのか。',lunHost:'湿地まで行ったんだね。靴は、火から少し離して乾かすんだよ。',lunBoat:'あそこの浅い水には、舟より板の道が向いている。',lunWatcher:'リスの包みなら、時々ここまで届く。布を替える時期が、雨で変わるんだ。'};
 for(const c of dialogue.characters){const previous=c.eventReply;c.eventReply=args=>{if(stay.data.threads.bell?.anomalyDay===stay.data.currentDay&&townLife.state.period==='night')return previous?.(args);return seen('mire:visit')&&args.index%4===1&&lines[c.id]?lines[c.id]:previous?.(args);};}
 ambientAudio.zones.push({id:'mire-water',sourceId:'lake-water',area:'town',position:L.center,radius:35,gain:.028,enabled:mireOpen,src:null},{id:'mire-air',sourceId:'nine-wind',area:'town',position:[-467,5,-234],radius:30,gain:.016,enabled:mireOpen,src:null});
 function sync(){if(busy)return;busy=true;try{setMireUnlocked(seen('mire:exit'));mire.root.visible=mireOpen();mire.flood.visible=mireOpen()&&!crownOpen();const t=stay.data.threads.violetMire??={stage:'unseen'};t.stage=seen('mire:reflection')?'reflected':seen('mire:visit')?'visited':seen('mire:exit')?'exit':'unseen';if(lastAvailable!==mireOpen()){lastAvailable=mireOpen();residentDay.refreshSchedules(e=>e.community?.regionId==='violet-mire');regions.refresh();}for(const c of controllers)if(!mireOpen())c.record.object.visible=false;}finally{busy=false;}}
 stay.onChange(sync);townLife.onChange(sync);sync();
 return{controllers,remember,sync,update(dt){elapsed+=dt;if(elapsed<.5)return;const step=elapsed;elapsed=0;sync();const current=regions.current.id,budget=regionActivity(current,'violet-mire',getQuality());const distance=Math.hypot(camera.position.x+458,camera.position.z+216);mire.detailBatch.visible=mireOpen()&&(budget.details||distance<120);mire.details.visible=mireOpen()&&(budget.details||distance<45);if(walking.active&&mireOpen()&&walking.state.feet.z<-182.5&&mireHeight(walking.state.feet.x,walking.state.feet.z)!==null&&!deep(walking.state.feet.x,walking.state.feet.z)){remember('mire:visit','石の空洞を抜けた先に、木道と小さな水面の続く湿地があった。');remember('region:violet-mire','Violet Mireの木道に立った。風より、湿った草の匂いが近い。');}const season=townLife.state.season??stay.data.season,weather=townLife.state.weather;if(lastSeason!==season||lastWeather!==weather){lastSeason=season;lastWeather=weather;const p=mireSeasonProfiles[season]??mireSeasonProfiles.spring;mire.materials.grass.color.setHex(p.grass);mire.materials.flower.color.setHex(season==='autumn'?0x7a7183:0x8d8295);for(const o of mire.flowers)o.count=Math.max(1,Math.round(o.userData.maximumCount*p.flowers));mire.materials.water.color.setHex(weather==='rain'?0x3b4c49:weather==='dawn'?0x58626b:0x455e5b);}if(budget.animate){plantTime+=step;for(let j=0;j<mire.plants.length;j++){const o=mire.plants[j];for(let i=0;i<mire.plantBases[j].length;i++){const m=mire.plantBases[j][i].clone();m.elements[4]+=.025*Math.sin(plantTime*.6+i);o.setMatrixAt(i,m);}o.instanceMatrix.needsUpdate=true;}}if(budget.details&&scene.fog){originalFog??=scene.fog.density;const base={clear:.005,rain:.008,fog:.012,dawn:.006,night:.007,blackout:.007}[weather]??.005,strength=weather==='fog'?regionalAtmospheres['violet-mire'].fogScale:1;scene.fog.density+=(base*strength-scene.fog.density)*Math.min(1,step);}else if(originalFog!==null&&scene.fog){scene.fog.density=originalFog;originalFog=null;}}};
}
