import assert from 'node:assert/strict';
import {capitalWards,capitalCharacters,capitalFacilities,capitalLinks,capitalRoad,capitalEvents} from '../caer-veyra-data.js';
import {defaultStay,validateStay} from '../stay-state.js';
import {evaluateConditions,deriveProgression} from '../progression-data.js';
import {worldSnapshot} from '../world-graph.js';
import {regionActivity} from '../region-activity.js';
const d=defaultStay();assert.equal(capitalWards.length,5);assert.equal(capitalCharacters.length,14);assert.equal(new Set(capitalCharacters.map(c=>c.id)).size,14);assert.equal(evaluateConditions('capital-lowerWard',d),false);
d.discoveries['region:violet-mire']={day:20};assert.ok(evaluateConditions('capital-lowerWard',d));assert.equal(evaluateConditions('capital-canalWard',d),false);d.currentDay=25;d.discoveries['cv:arrival']={day:25};d.discoveries['cv:market']={day:25};assert.equal(evaluateConditions('capital-canalWard',d),false);d.currentDay++;assert.ok(evaluateConditions('capital-canalWard',d));d.currentDay=29;d.discoveries['region:caer-canalWard']={day:26};d.discoveries['cv:canal-level']={day:26};assert.ok(evaluateConditions('capital-civicWard',d));d.discoveries['region:caer-civicWard']={day:27};d.discoveries['cv:archive-catalog']={day:27};assert.ok(evaluateConditions('capital-scholarHeights',d));d.discoveries['region:caer-scholarHeights']={day:28};assert.equal(evaluateConditions('capital-oldQuarter',d),false);for(const id of ['cv:old-map','cv:elda-direction','cv:cat-old-entry']){d.discoveries[id]={day:29};assert.ok(evaluateConditions('capital-oldQuarter',d));delete d.discoveries[id];}
for(const c of capitalCharacters){assert.ok(capitalFacilities.some(s=>s.id===c.mainLocation));d.memories[c.id]={human:{visits:2,firstDay:25,lastDay:29}};}for(const e of capitalEvents)d.events[e.id]={state:'noticed',noticedDay:29};d.threads.caerVeyraRecords={stage:'compared'};d.discoveries['cv:finn-val']={day:29};const restored=validateStay(d);assert.equal(restored.threads.caerVeyraRecords.stage,'compared');for(const c of capitalCharacters)assert.equal(restored.memories[c.id].human.visits,2);for(const e of capitalEvents)assert.equal(restored.events[e.id].noticedDay,29);assert.ok(restored.discoveries['cv:finn-val']);assert.equal(deriveProgression(restored).chapters.capital,'present');assert.ok(worldSnapshot(defaultStay()).nodes.find(n=>n.id==='caer-veyra').hidden);
assert.equal(regionActivity('caer-oldQuarter','bellmire').activity,'dormant');assert.equal(regionActivity('caer-civicWard','caer-scholarHeights').activity,'nearby');assert.equal(regionActivity('caer-lowerWard','caer-oldQuarter').activity,'background');assert.ok(capitalLinks.every(l=>capitalWards.some(w=>w.id===l.from)&&capitalWards.some(w=>w.id===l.to)));console.log('PASS arrival-relative ward pacing, three independent old-street clues, 14 memories/events migration, hidden city, chapter and subregion budgets; royal road '+capitalRoad.slice(1).reduce((n,p,i)=>n+Math.hypot(p[0]-capitalRoad[i][0],p[2]-capitalRoad[i][2]),0).toFixed(1)+'m');
