import assert from 'node:assert/strict';
import {watercourseLayout as w} from '../waterways.js';
const points=[w.source,...w.upper,...w.falls,...w.open,...w.feed.slice(1),...w.lower.slice(1)];
assert.ok(points.every((p,i)=>!i||p[1]<=points[i-1][1]),'water must never run uphill');
assert.deepEqual(w.open.at(-1),w.feed[0]);
assert.deepEqual(w.feed.at(-1),w.lower[0]);
assert.ok(w.timberLength<1.1);
assert.deepEqual(w.source,w.springBasin.center);
assert.ok(w.source[1]>8.2 && w.source[1]<8.5,'spring is on the upper housing plateau');
assert.ok(w.upper[0][2]<=w.source[2]+w.springBasin.radius[1]+.1,'pond connects to short upper stream');
assert.deepEqual(w.upper.at(-1),w.falls[0]);
assert.ok(w.source[0]-w.springBasin.lookout[0]>w.springBasin.radius[0]+.3,'dry bank outside water');
assert.ok(4.7/15<.38,'supported approach rises fit human profile');
assert.equal(w.falls.filter((p,i)=>i&&p[2]===w.falls[i-1][2]).length,2);
assert.ok(w.falls.every((p,i)=>!i||w.falls[i-1][1]-p[1]<=2.01),'two modest falls fit the existing terrace height');
assert.ok(Math.abs(w.lower.at(-1)[1]-1.23)<.001);
const paddleBottom=w.wheel[1]-.55*(3.65+1.15/2);
assert.ok(paddleBottom<3.77&&paddleBottom>3.57,'lower blades touch the shallow mill pool');
for(const b of w.bridges){const ground=b.id==='quay'?1.38:3.5;assert.ok((b.water+.24-ground)/(b.id==='quay'?3:2)<.38,'approach rises respect human step height');}
console.log('PASS one downhill spring-open-leat-wheel-harbor layout / short timber feed / blade contact / bridge risers');
